// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package msgraphconnector.proxies;

public class Application
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject applicationMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MSGraphConnector.Application";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ApplicationId("ApplicationId"),
		Name("Name"),
		ClientId("ClientId"),
		TenantId("TenantId"),
		Secret("Secret"),
		RedirectUrl("RedirectUrl"),
		UserId_MSGraph("UserId_MSGraph"),
		ErrorHandling("ErrorHandling"),
		Application_Permission("MSGraphConnector.Application_Permission");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Application(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MSGraphConnector.Application"));
	}

	protected Application(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject applicationMendixObject)
	{
		if (applicationMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MSGraphConnector.Application", applicationMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MSGraphConnector.Application");

		this.applicationMendixObject = applicationMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Application.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static msgraphconnector.proxies.Application initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return msgraphconnector.proxies.Application.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static msgraphconnector.proxies.Application initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new msgraphconnector.proxies.Application(context, mendixObject);
	}

	public static msgraphconnector.proxies.Application load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return msgraphconnector.proxies.Application.initialize(context, mendixObject);
	}

	public static java.util.List<msgraphconnector.proxies.Application> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<msgraphconnector.proxies.Application> result = new java.util.ArrayList<msgraphconnector.proxies.Application>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//MSGraphConnector.Application" + xpathConstraint))
			result.add(msgraphconnector.proxies.Application.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of ApplicationId
	 */
	public final java.lang.Long getApplicationId()
	{
		return getApplicationId(getContext());
	}

	/**
	 * @param context
	 * @return value of ApplicationId
	 */
	public final java.lang.Long getApplicationId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.ApplicationId.toString());
	}

	/**
	 * Set value of ApplicationId
	 * @param applicationid
	 */
	public final void setApplicationId(java.lang.Long applicationid)
	{
		setApplicationId(getContext(), applicationid);
	}

	/**
	 * Set value of ApplicationId
	 * @param context
	 * @param applicationid
	 */
	public final void setApplicationId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long applicationid)
	{
		getMendixObject().setValue(context, MemberNames.ApplicationId.toString(), applicationid);
	}

	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of ClientId
	 */
	public final java.lang.String getClientId()
	{
		return getClientId(getContext());
	}

	/**
	 * @param context
	 * @return value of ClientId
	 */
	public final java.lang.String getClientId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ClientId.toString());
	}

	/**
	 * Set value of ClientId
	 * @param clientid
	 */
	public final void setClientId(java.lang.String clientid)
	{
		setClientId(getContext(), clientid);
	}

	/**
	 * Set value of ClientId
	 * @param context
	 * @param clientid
	 */
	public final void setClientId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String clientid)
	{
		getMendixObject().setValue(context, MemberNames.ClientId.toString(), clientid);
	}

	/**
	 * @return value of TenantId
	 */
	public final java.lang.String getTenantId()
	{
		return getTenantId(getContext());
	}

	/**
	 * @param context
	 * @return value of TenantId
	 */
	public final java.lang.String getTenantId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.TenantId.toString());
	}

	/**
	 * Set value of TenantId
	 * @param tenantid
	 */
	public final void setTenantId(java.lang.String tenantid)
	{
		setTenantId(getContext(), tenantid);
	}

	/**
	 * Set value of TenantId
	 * @param context
	 * @param tenantid
	 */
	public final void setTenantId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String tenantid)
	{
		getMendixObject().setValue(context, MemberNames.TenantId.toString(), tenantid);
	}

	/**
	 * @return value of Secret
	 */
	public final java.lang.String getSecret()
	{
		return getSecret(getContext());
	}

	/**
	 * @param context
	 * @return value of Secret
	 */
	public final java.lang.String getSecret(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Secret.toString());
	}

	/**
	 * Set value of Secret
	 * @param secret
	 */
	public final void setSecret(java.lang.String secret)
	{
		setSecret(getContext(), secret);
	}

	/**
	 * Set value of Secret
	 * @param context
	 * @param secret
	 */
	public final void setSecret(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String secret)
	{
		getMendixObject().setValue(context, MemberNames.Secret.toString(), secret);
	}

	/**
	 * @return value of RedirectUrl
	 */
	public final java.lang.String getRedirectUrl()
	{
		return getRedirectUrl(getContext());
	}

	/**
	 * @param context
	 * @return value of RedirectUrl
	 */
	public final java.lang.String getRedirectUrl(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.RedirectUrl.toString());
	}

	/**
	 * Set value of RedirectUrl
	 * @param redirecturl
	 */
	public final void setRedirectUrl(java.lang.String redirecturl)
	{
		setRedirectUrl(getContext(), redirecturl);
	}

	/**
	 * Set value of RedirectUrl
	 * @param context
	 * @param redirecturl
	 */
	public final void setRedirectUrl(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String redirecturl)
	{
		getMendixObject().setValue(context, MemberNames.RedirectUrl.toString(), redirecturl);
	}

	/**
	 * @return value of UserId_MSGraph
	 */
	public final java.lang.String getUserId_MSGraph()
	{
		return getUserId_MSGraph(getContext());
	}

	/**
	 * @param context
	 * @return value of UserId_MSGraph
	 */
	public final java.lang.String getUserId_MSGraph(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.UserId_MSGraph.toString());
	}

	/**
	 * Set value of UserId_MSGraph
	 * @param userid_msgraph
	 */
	public final void setUserId_MSGraph(java.lang.String userid_msgraph)
	{
		setUserId_MSGraph(getContext(), userid_msgraph);
	}

	/**
	 * Set value of UserId_MSGraph
	 * @param context
	 * @param userid_msgraph
	 */
	public final void setUserId_MSGraph(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String userid_msgraph)
	{
		getMendixObject().setValue(context, MemberNames.UserId_MSGraph.toString(), userid_msgraph);
	}

	/**
	 * Set value of ErrorHandling
	 * @param errorhandling
	 */
	public final msgraphconnector.proxies.ApplicationErrorHandling getErrorHandling()
	{
		return getErrorHandling(getContext());
	}

	/**
	 * @param context
	 * @return value of ErrorHandling
	 */
	public final msgraphconnector.proxies.ApplicationErrorHandling getErrorHandling(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.ErrorHandling.toString());
		if (obj == null)
			return null;

		return msgraphconnector.proxies.ApplicationErrorHandling.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of ErrorHandling
	 * @param errorhandling
	 */
	public final void setErrorHandling(msgraphconnector.proxies.ApplicationErrorHandling errorhandling)
	{
		setErrorHandling(getContext(), errorhandling);
	}

	/**
	 * Set value of ErrorHandling
	 * @param context
	 * @param errorhandling
	 */
	public final void setErrorHandling(com.mendix.systemwideinterfaces.core.IContext context, msgraphconnector.proxies.ApplicationErrorHandling errorhandling)
	{
		if (errorhandling != null)
			getMendixObject().setValue(context, MemberNames.ErrorHandling.toString(), errorhandling.toString());
		else
			getMendixObject().setValue(context, MemberNames.ErrorHandling.toString(), null);
	}

	/**
	 * @return value of Application_Permission
	 */
	public final java.util.List<msgraphconnector.proxies.Permission> getApplication_Permission() throws com.mendix.core.CoreException
	{
		return getApplication_Permission(getContext());
	}

	/**
	 * @param context
	 * @return value of Application_Permission
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<msgraphconnector.proxies.Permission> getApplication_Permission(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<msgraphconnector.proxies.Permission> result = new java.util.ArrayList<msgraphconnector.proxies.Permission>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.Application_Permission.toString());
		if (valueObject == null)
			return result;
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject))
			result.add(msgraphconnector.proxies.Permission.initialize(context, mendixObject));
		return result;
	}

	/**
	 * Set value of Application_Permission
	 * @param application_permission
	 */
	public final void setApplication_Permission(java.util.List<msgraphconnector.proxies.Permission> application_permission)
	{
		setApplication_Permission(getContext(), application_permission);
	}

	/**
	 * Set value of Application_Permission
	 * @param context
	 * @param application_permission
	 */
	public final void setApplication_Permission(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<msgraphconnector.proxies.Permission> application_permission)
	{
		java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier> identifiers = new java.util.ArrayList<com.mendix.systemwideinterfaces.core.IMendixIdentifier>();
		for (msgraphconnector.proxies.Permission proxyObject : application_permission)
			identifiers.add(proxyObject.getMendixObject().getId());
		getMendixObject().setValue(context, MemberNames.Application_Permission.toString(), identifiers);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return applicationMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final msgraphconnector.proxies.Application that = (msgraphconnector.proxies.Application) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MSGraphConnector.Application";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
