// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package msgraphconnector.proxies;

public class AuthToken
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject authTokenMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MSGraphConnector.AuthToken";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		TokenId("TokenId"),
		Token_Type("Token_Type"),
		Scope("Scope"),
		Expires_In("Expires_In"),
		Ext_Expires_In("Ext_Expires_In"),
		Access_Token("Access_Token"),
		Refresh_Token("Refresh_Token"),
		Created_Date("Created_Date"),
		Expiry_Date("Expiry_Date"),
		AuthToken_User("MSGraphConnector.AuthToken_User");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public AuthToken(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MSGraphConnector.AuthToken"));
	}

	protected AuthToken(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject authTokenMendixObject)
	{
		if (authTokenMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MSGraphConnector.AuthToken", authTokenMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MSGraphConnector.AuthToken");

		this.authTokenMendixObject = authTokenMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'AuthToken.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static msgraphconnector.proxies.AuthToken initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return msgraphconnector.proxies.AuthToken.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static msgraphconnector.proxies.AuthToken initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new msgraphconnector.proxies.AuthToken(context, mendixObject);
	}

	public static msgraphconnector.proxies.AuthToken load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return msgraphconnector.proxies.AuthToken.initialize(context, mendixObject);
	}

	public static java.util.List<msgraphconnector.proxies.AuthToken> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<msgraphconnector.proxies.AuthToken> result = new java.util.ArrayList<msgraphconnector.proxies.AuthToken>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//MSGraphConnector.AuthToken" + xpathConstraint))
			result.add(msgraphconnector.proxies.AuthToken.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of TokenId
	 */
	public final java.lang.Long getTokenId()
	{
		return getTokenId(getContext());
	}

	/**
	 * @param context
	 * @return value of TokenId
	 */
	public final java.lang.Long getTokenId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.TokenId.toString());
	}

	/**
	 * Set value of TokenId
	 * @param tokenid
	 */
	public final void setTokenId(java.lang.Long tokenid)
	{
		setTokenId(getContext(), tokenid);
	}

	/**
	 * Set value of TokenId
	 * @param context
	 * @param tokenid
	 */
	public final void setTokenId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long tokenid)
	{
		getMendixObject().setValue(context, MemberNames.TokenId.toString(), tokenid);
	}

	/**
	 * @return value of Token_Type
	 */
	public final java.lang.String getToken_Type()
	{
		return getToken_Type(getContext());
	}

	/**
	 * @param context
	 * @return value of Token_Type
	 */
	public final java.lang.String getToken_Type(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Token_Type.toString());
	}

	/**
	 * Set value of Token_Type
	 * @param token_type
	 */
	public final void setToken_Type(java.lang.String token_type)
	{
		setToken_Type(getContext(), token_type);
	}

	/**
	 * Set value of Token_Type
	 * @param context
	 * @param token_type
	 */
	public final void setToken_Type(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String token_type)
	{
		getMendixObject().setValue(context, MemberNames.Token_Type.toString(), token_type);
	}

	/**
	 * @return value of Scope
	 */
	public final java.lang.String getScope()
	{
		return getScope(getContext());
	}

	/**
	 * @param context
	 * @return value of Scope
	 */
	public final java.lang.String getScope(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Scope.toString());
	}

	/**
	 * Set value of Scope
	 * @param scope
	 */
	public final void setScope(java.lang.String scope)
	{
		setScope(getContext(), scope);
	}

	/**
	 * Set value of Scope
	 * @param context
	 * @param scope
	 */
	public final void setScope(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String scope)
	{
		getMendixObject().setValue(context, MemberNames.Scope.toString(), scope);
	}

	/**
	 * @return value of Expires_In
	 */
	public final java.lang.Integer getExpires_In()
	{
		return getExpires_In(getContext());
	}

	/**
	 * @param context
	 * @return value of Expires_In
	 */
	public final java.lang.Integer getExpires_In(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Expires_In.toString());
	}

	/**
	 * Set value of Expires_In
	 * @param expires_in
	 */
	public final void setExpires_In(java.lang.Integer expires_in)
	{
		setExpires_In(getContext(), expires_in);
	}

	/**
	 * Set value of Expires_In
	 * @param context
	 * @param expires_in
	 */
	public final void setExpires_In(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer expires_in)
	{
		getMendixObject().setValue(context, MemberNames.Expires_In.toString(), expires_in);
	}

	/**
	 * @return value of Ext_Expires_In
	 */
	public final java.lang.Integer getExt_Expires_In()
	{
		return getExt_Expires_In(getContext());
	}

	/**
	 * @param context
	 * @return value of Ext_Expires_In
	 */
	public final java.lang.Integer getExt_Expires_In(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Ext_Expires_In.toString());
	}

	/**
	 * Set value of Ext_Expires_In
	 * @param ext_expires_in
	 */
	public final void setExt_Expires_In(java.lang.Integer ext_expires_in)
	{
		setExt_Expires_In(getContext(), ext_expires_in);
	}

	/**
	 * Set value of Ext_Expires_In
	 * @param context
	 * @param ext_expires_in
	 */
	public final void setExt_Expires_In(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer ext_expires_in)
	{
		getMendixObject().setValue(context, MemberNames.Ext_Expires_In.toString(), ext_expires_in);
	}

	/**
	 * @return value of Access_Token
	 */
	public final java.lang.String getAccess_Token()
	{
		return getAccess_Token(getContext());
	}

	/**
	 * @param context
	 * @return value of Access_Token
	 */
	public final java.lang.String getAccess_Token(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Access_Token.toString());
	}

	/**
	 * Set value of Access_Token
	 * @param access_token
	 */
	public final void setAccess_Token(java.lang.String access_token)
	{
		setAccess_Token(getContext(), access_token);
	}

	/**
	 * Set value of Access_Token
	 * @param context
	 * @param access_token
	 */
	public final void setAccess_Token(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String access_token)
	{
		getMendixObject().setValue(context, MemberNames.Access_Token.toString(), access_token);
	}

	/**
	 * @return value of Refresh_Token
	 */
	public final java.lang.String getRefresh_Token()
	{
		return getRefresh_Token(getContext());
	}

	/**
	 * @param context
	 * @return value of Refresh_Token
	 */
	public final java.lang.String getRefresh_Token(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Refresh_Token.toString());
	}

	/**
	 * Set value of Refresh_Token
	 * @param refresh_token
	 */
	public final void setRefresh_Token(java.lang.String refresh_token)
	{
		setRefresh_Token(getContext(), refresh_token);
	}

	/**
	 * Set value of Refresh_Token
	 * @param context
	 * @param refresh_token
	 */
	public final void setRefresh_Token(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String refresh_token)
	{
		getMendixObject().setValue(context, MemberNames.Refresh_Token.toString(), refresh_token);
	}

	/**
	 * @return value of Created_Date
	 */
	public final java.util.Date getCreated_Date()
	{
		return getCreated_Date(getContext());
	}

	/**
	 * @param context
	 * @return value of Created_Date
	 */
	public final java.util.Date getCreated_Date(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.Created_Date.toString());
	}

	/**
	 * Set value of Created_Date
	 * @param created_date
	 */
	public final void setCreated_Date(java.util.Date created_date)
	{
		setCreated_Date(getContext(), created_date);
	}

	/**
	 * Set value of Created_Date
	 * @param context
	 * @param created_date
	 */
	public final void setCreated_Date(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date created_date)
	{
		getMendixObject().setValue(context, MemberNames.Created_Date.toString(), created_date);
	}

	/**
	 * @return value of Expiry_Date
	 */
	public final java.util.Date getExpiry_Date()
	{
		return getExpiry_Date(getContext());
	}

	/**
	 * @param context
	 * @return value of Expiry_Date
	 */
	public final java.util.Date getExpiry_Date(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.Expiry_Date.toString());
	}

	/**
	 * Set value of Expiry_Date
	 * @param expiry_date
	 */
	public final void setExpiry_Date(java.util.Date expiry_date)
	{
		setExpiry_Date(getContext(), expiry_date);
	}

	/**
	 * Set value of Expiry_Date
	 * @param context
	 * @param expiry_date
	 */
	public final void setExpiry_Date(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date expiry_date)
	{
		getMendixObject().setValue(context, MemberNames.Expiry_Date.toString(), expiry_date);
	}

	/**
	 * @return value of AuthToken_User
	 */
	public final system.proxies.User getAuthToken_User() throws com.mendix.core.CoreException
	{
		return getAuthToken_User(getContext());
	}

	/**
	 * @param context
	 * @return value of AuthToken_User
	 */
	public final system.proxies.User getAuthToken_User(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		system.proxies.User result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.AuthToken_User.toString());
		if (identifier != null)
			result = system.proxies.User.load(context, identifier);
		return result;
	}

	/**
	 * Set value of AuthToken_User
	 * @param authtoken_user
	 */
	public final void setAuthToken_User(system.proxies.User authtoken_user)
	{
		setAuthToken_User(getContext(), authtoken_user);
	}

	/**
	 * Set value of AuthToken_User
	 * @param context
	 * @param authtoken_user
	 */
	public final void setAuthToken_User(com.mendix.systemwideinterfaces.core.IContext context, system.proxies.User authtoken_user)
	{
		if (authtoken_user == null)
			getMendixObject().setValue(context, MemberNames.AuthToken_User.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.AuthToken_User.toString(), authtoken_user.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return authTokenMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final msgraphconnector.proxies.AuthToken that = (msgraphconnector.proxies.AuthToken) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MSGraphConnector.AuthToken";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
