// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package msgraphconnector.proxies;

public class BaseItemSharepointIds
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject baseItemSharepointIdsMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MSGraphConnector.BaseItemSharepointIds";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ListId("ListId"),
		ListItemId("ListItemId"),
		ListItemUniqueId("ListItemUniqueId"),
		SiteId("SiteId"),
		SiteUrl("SiteUrl"),
		WebId("WebId"),
		BaseItemSharepointIds_BaseItemParentReference("MSGraphConnector.BaseItemSharepointIds_BaseItemParentReference");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public BaseItemSharepointIds(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MSGraphConnector.BaseItemSharepointIds"));
	}

	protected BaseItemSharepointIds(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject baseItemSharepointIdsMendixObject)
	{
		if (baseItemSharepointIdsMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MSGraphConnector.BaseItemSharepointIds", baseItemSharepointIdsMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MSGraphConnector.BaseItemSharepointIds");

		this.baseItemSharepointIdsMendixObject = baseItemSharepointIdsMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'BaseItemSharepointIds.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static msgraphconnector.proxies.BaseItemSharepointIds initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return msgraphconnector.proxies.BaseItemSharepointIds.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static msgraphconnector.proxies.BaseItemSharepointIds initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new msgraphconnector.proxies.BaseItemSharepointIds(context, mendixObject);
	}

	public static msgraphconnector.proxies.BaseItemSharepointIds load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return msgraphconnector.proxies.BaseItemSharepointIds.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of ListId
	 */
	public final java.lang.String getListId()
	{
		return getListId(getContext());
	}

	/**
	 * @param context
	 * @return value of ListId
	 */
	public final java.lang.String getListId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ListId.toString());
	}

	/**
	 * Set value of ListId
	 * @param listid
	 */
	public final void setListId(java.lang.String listid)
	{
		setListId(getContext(), listid);
	}

	/**
	 * Set value of ListId
	 * @param context
	 * @param listid
	 */
	public final void setListId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String listid)
	{
		getMendixObject().setValue(context, MemberNames.ListId.toString(), listid);
	}

	/**
	 * @return value of ListItemId
	 */
	public final java.lang.String getListItemId()
	{
		return getListItemId(getContext());
	}

	/**
	 * @param context
	 * @return value of ListItemId
	 */
	public final java.lang.String getListItemId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ListItemId.toString());
	}

	/**
	 * Set value of ListItemId
	 * @param listitemid
	 */
	public final void setListItemId(java.lang.String listitemid)
	{
		setListItemId(getContext(), listitemid);
	}

	/**
	 * Set value of ListItemId
	 * @param context
	 * @param listitemid
	 */
	public final void setListItemId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String listitemid)
	{
		getMendixObject().setValue(context, MemberNames.ListItemId.toString(), listitemid);
	}

	/**
	 * @return value of ListItemUniqueId
	 */
	public final java.lang.String getListItemUniqueId()
	{
		return getListItemUniqueId(getContext());
	}

	/**
	 * @param context
	 * @return value of ListItemUniqueId
	 */
	public final java.lang.String getListItemUniqueId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ListItemUniqueId.toString());
	}

	/**
	 * Set value of ListItemUniqueId
	 * @param listitemuniqueid
	 */
	public final void setListItemUniqueId(java.lang.String listitemuniqueid)
	{
		setListItemUniqueId(getContext(), listitemuniqueid);
	}

	/**
	 * Set value of ListItemUniqueId
	 * @param context
	 * @param listitemuniqueid
	 */
	public final void setListItemUniqueId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String listitemuniqueid)
	{
		getMendixObject().setValue(context, MemberNames.ListItemUniqueId.toString(), listitemuniqueid);
	}

	/**
	 * @return value of SiteId
	 */
	public final java.lang.String getSiteId()
	{
		return getSiteId(getContext());
	}

	/**
	 * @param context
	 * @return value of SiteId
	 */
	public final java.lang.String getSiteId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.SiteId.toString());
	}

	/**
	 * Set value of SiteId
	 * @param siteid
	 */
	public final void setSiteId(java.lang.String siteid)
	{
		setSiteId(getContext(), siteid);
	}

	/**
	 * Set value of SiteId
	 * @param context
	 * @param siteid
	 */
	public final void setSiteId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String siteid)
	{
		getMendixObject().setValue(context, MemberNames.SiteId.toString(), siteid);
	}

	/**
	 * @return value of SiteUrl
	 */
	public final java.lang.String getSiteUrl()
	{
		return getSiteUrl(getContext());
	}

	/**
	 * @param context
	 * @return value of SiteUrl
	 */
	public final java.lang.String getSiteUrl(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.SiteUrl.toString());
	}

	/**
	 * Set value of SiteUrl
	 * @param siteurl
	 */
	public final void setSiteUrl(java.lang.String siteurl)
	{
		setSiteUrl(getContext(), siteurl);
	}

	/**
	 * Set value of SiteUrl
	 * @param context
	 * @param siteurl
	 */
	public final void setSiteUrl(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String siteurl)
	{
		getMendixObject().setValue(context, MemberNames.SiteUrl.toString(), siteurl);
	}

	/**
	 * @return value of WebId
	 */
	public final java.lang.String getWebId()
	{
		return getWebId(getContext());
	}

	/**
	 * @param context
	 * @return value of WebId
	 */
	public final java.lang.String getWebId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.WebId.toString());
	}

	/**
	 * Set value of WebId
	 * @param webid
	 */
	public final void setWebId(java.lang.String webid)
	{
		setWebId(getContext(), webid);
	}

	/**
	 * Set value of WebId
	 * @param context
	 * @param webid
	 */
	public final void setWebId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String webid)
	{
		getMendixObject().setValue(context, MemberNames.WebId.toString(), webid);
	}

	/**
	 * @return value of BaseItemSharepointIds_BaseItemParentReference
	 */
	public final msgraphconnector.proxies.BaseItemParentReference getBaseItemSharepointIds_BaseItemParentReference() throws com.mendix.core.CoreException
	{
		return getBaseItemSharepointIds_BaseItemParentReference(getContext());
	}

	/**
	 * @param context
	 * @return value of BaseItemSharepointIds_BaseItemParentReference
	 */
	public final msgraphconnector.proxies.BaseItemParentReference getBaseItemSharepointIds_BaseItemParentReference(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		msgraphconnector.proxies.BaseItemParentReference result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.BaseItemSharepointIds_BaseItemParentReference.toString());
		if (identifier != null)
			result = msgraphconnector.proxies.BaseItemParentReference.load(context, identifier);
		return result;
	}

	/**
	 * Set value of BaseItemSharepointIds_BaseItemParentReference
	 * @param baseitemsharepointids_baseitemparentreference
	 */
	public final void setBaseItemSharepointIds_BaseItemParentReference(msgraphconnector.proxies.BaseItemParentReference baseitemsharepointids_baseitemparentreference)
	{
		setBaseItemSharepointIds_BaseItemParentReference(getContext(), baseitemsharepointids_baseitemparentreference);
	}

	/**
	 * Set value of BaseItemSharepointIds_BaseItemParentReference
	 * @param context
	 * @param baseitemsharepointids_baseitemparentreference
	 */
	public final void setBaseItemSharepointIds_BaseItemParentReference(com.mendix.systemwideinterfaces.core.IContext context, msgraphconnector.proxies.BaseItemParentReference baseitemsharepointids_baseitemparentreference)
	{
		if (baseitemsharepointids_baseitemparentreference == null)
			getMendixObject().setValue(context, MemberNames.BaseItemSharepointIds_BaseItemParentReference.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.BaseItemSharepointIds_BaseItemParentReference.toString(), baseitemsharepointids_baseitemparentreference.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return baseItemSharepointIdsMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final msgraphconnector.proxies.BaseItemSharepointIds that = (msgraphconnector.proxies.BaseItemSharepointIds) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MSGraphConnector.BaseItemSharepointIds";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
