// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package msgraphconnector.proxies;

public class BaseItemCreatedBy extends msgraphconnector.proxies.BaseItemIdentitySet
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MSGraphConnector.BaseItemCreatedBy";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		BaseItemCreatedBy_BaseItem("MSGraphConnector.BaseItemCreatedBy_BaseItem"),
		BaseItemIdentity_Application_BaseItemIdentity("MSGraphConnector.BaseItemIdentity_Application_BaseItemIdentity"),
		BaseItemIdentity_Device_BaseItemIdentity("MSGraphConnector.BaseItemIdentity_Device_BaseItemIdentity"),
		BaseItemIdentity_User_BaseItemIdentity("MSGraphConnector.BaseItemIdentity_User_BaseItemIdentity");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public BaseItemCreatedBy(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MSGraphConnector.BaseItemCreatedBy"));
	}

	protected BaseItemCreatedBy(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject baseItemCreatedByMendixObject)
	{
		super(context, baseItemCreatedByMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("MSGraphConnector.BaseItemCreatedBy", baseItemCreatedByMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MSGraphConnector.BaseItemCreatedBy");
	}

	/**
	 * @deprecated Use 'BaseItemCreatedBy.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static msgraphconnector.proxies.BaseItemCreatedBy initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return msgraphconnector.proxies.BaseItemCreatedBy.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static msgraphconnector.proxies.BaseItemCreatedBy initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new msgraphconnector.proxies.BaseItemCreatedBy(context, mendixObject);
	}

	public static msgraphconnector.proxies.BaseItemCreatedBy load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return msgraphconnector.proxies.BaseItemCreatedBy.initialize(context, mendixObject);
	}

	/**
	 * @return value of BaseItemCreatedBy_BaseItem
	 */
	public final msgraphconnector.proxies.BaseItem getBaseItemCreatedBy_BaseItem() throws com.mendix.core.CoreException
	{
		return getBaseItemCreatedBy_BaseItem(getContext());
	}

	/**
	 * @param context
	 * @return value of BaseItemCreatedBy_BaseItem
	 */
	public final msgraphconnector.proxies.BaseItem getBaseItemCreatedBy_BaseItem(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		msgraphconnector.proxies.BaseItem result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.BaseItemCreatedBy_BaseItem.toString());
		if (identifier != null)
			result = msgraphconnector.proxies.BaseItem.load(context, identifier);
		return result;
	}

	/**
	 * Set value of BaseItemCreatedBy_BaseItem
	 * @param baseitemcreatedby_baseitem
	 */
	public final void setBaseItemCreatedBy_BaseItem(msgraphconnector.proxies.BaseItem baseitemcreatedby_baseitem)
	{
		setBaseItemCreatedBy_BaseItem(getContext(), baseitemcreatedby_baseitem);
	}

	/**
	 * Set value of BaseItemCreatedBy_BaseItem
	 * @param context
	 * @param baseitemcreatedby_baseitem
	 */
	public final void setBaseItemCreatedBy_BaseItem(com.mendix.systemwideinterfaces.core.IContext context, msgraphconnector.proxies.BaseItem baseitemcreatedby_baseitem)
	{
		if (baseitemcreatedby_baseitem == null)
			getMendixObject().setValue(context, MemberNames.BaseItemCreatedBy_BaseItem.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.BaseItemCreatedBy_BaseItem.toString(), baseitemcreatedby_baseitem.getMendixObject().getId());
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final msgraphconnector.proxies.BaseItemCreatedBy that = (msgraphconnector.proxies.BaseItemCreatedBy) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MSGraphConnector.BaseItemCreatedBy";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
