// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package msgraphconnector.proxies;

public class BaseItem
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject baseItemMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MSGraphConnector.BaseItem";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		_id("_id"),
		CreatedDateTime("CreatedDateTime"),
		Description("Description"),
		eTag("eTag"),
		LastModifiedDateTime("LastModifiedDateTime"),
		Name("Name"),
		WebUrl("WebUrl"),
		BaseItemCreatedBy_BaseItem("MSGraphConnector.BaseItemCreatedBy_BaseItem"),
		BaseItemLastModifiedBy_BaseItem("MSGraphConnector.BaseItemLastModifiedBy_BaseItem"),
		BaseItemParentReference_BaseItem("MSGraphConnector.BaseItemParentReference_BaseItem");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public BaseItem(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MSGraphConnector.BaseItem"));
	}

	protected BaseItem(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject baseItemMendixObject)
	{
		if (baseItemMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MSGraphConnector.BaseItem", baseItemMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MSGraphConnector.BaseItem");

		this.baseItemMendixObject = baseItemMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'BaseItem.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static msgraphconnector.proxies.BaseItem initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return msgraphconnector.proxies.BaseItem.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static msgraphconnector.proxies.BaseItem initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new msgraphconnector.proxies.BaseItem(context, mendixObject);
	}

	public static msgraphconnector.proxies.BaseItem load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return msgraphconnector.proxies.BaseItem.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of _id
	 */
	public final java.lang.String get_id()
	{
		return get_id(getContext());
	}

	/**
	 * @param context
	 * @return value of _id
	 */
	public final java.lang.String get_id(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames._id.toString());
	}

	/**
	 * Set value of _id
	 * @param _id
	 */
	public final void set_id(java.lang.String _id)
	{
		set_id(getContext(), _id);
	}

	/**
	 * Set value of _id
	 * @param context
	 * @param _id
	 */
	public final void set_id(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String _id)
	{
		getMendixObject().setValue(context, MemberNames._id.toString(), _id);
	}

	/**
	 * @return value of CreatedDateTime
	 */
	public final java.util.Date getCreatedDateTime()
	{
		return getCreatedDateTime(getContext());
	}

	/**
	 * @param context
	 * @return value of CreatedDateTime
	 */
	public final java.util.Date getCreatedDateTime(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.CreatedDateTime.toString());
	}

	/**
	 * Set value of CreatedDateTime
	 * @param createddatetime
	 */
	public final void setCreatedDateTime(java.util.Date createddatetime)
	{
		setCreatedDateTime(getContext(), createddatetime);
	}

	/**
	 * Set value of CreatedDateTime
	 * @param context
	 * @param createddatetime
	 */
	public final void setCreatedDateTime(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date createddatetime)
	{
		getMendixObject().setValue(context, MemberNames.CreatedDateTime.toString(), createddatetime);
	}

	/**
	 * @return value of Description
	 */
	public final java.lang.String getDescription()
	{
		return getDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of Description
	 */
	public final java.lang.String getDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Description.toString());
	}

	/**
	 * Set value of Description
	 * @param description
	 */
	public final void setDescription(java.lang.String description)
	{
		setDescription(getContext(), description);
	}

	/**
	 * Set value of Description
	 * @param context
	 * @param description
	 */
	public final void setDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String description)
	{
		getMendixObject().setValue(context, MemberNames.Description.toString(), description);
	}

	/**
	 * @return value of eTag
	 */
	public final java.lang.String geteTag()
	{
		return geteTag(getContext());
	}

	/**
	 * @param context
	 * @return value of eTag
	 */
	public final java.lang.String geteTag(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.eTag.toString());
	}

	/**
	 * Set value of eTag
	 * @param etag
	 */
	public final void seteTag(java.lang.String etag)
	{
		seteTag(getContext(), etag);
	}

	/**
	 * Set value of eTag
	 * @param context
	 * @param etag
	 */
	public final void seteTag(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String etag)
	{
		getMendixObject().setValue(context, MemberNames.eTag.toString(), etag);
	}

	/**
	 * @return value of LastModifiedDateTime
	 */
	public final java.util.Date getLastModifiedDateTime()
	{
		return getLastModifiedDateTime(getContext());
	}

	/**
	 * @param context
	 * @return value of LastModifiedDateTime
	 */
	public final java.util.Date getLastModifiedDateTime(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.LastModifiedDateTime.toString());
	}

	/**
	 * Set value of LastModifiedDateTime
	 * @param lastmodifieddatetime
	 */
	public final void setLastModifiedDateTime(java.util.Date lastmodifieddatetime)
	{
		setLastModifiedDateTime(getContext(), lastmodifieddatetime);
	}

	/**
	 * Set value of LastModifiedDateTime
	 * @param context
	 * @param lastmodifieddatetime
	 */
	public final void setLastModifiedDateTime(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date lastmodifieddatetime)
	{
		getMendixObject().setValue(context, MemberNames.LastModifiedDateTime.toString(), lastmodifieddatetime);
	}

	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of WebUrl
	 */
	public final java.lang.String getWebUrl()
	{
		return getWebUrl(getContext());
	}

	/**
	 * @param context
	 * @return value of WebUrl
	 */
	public final java.lang.String getWebUrl(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.WebUrl.toString());
	}

	/**
	 * Set value of WebUrl
	 * @param weburl
	 */
	public final void setWebUrl(java.lang.String weburl)
	{
		setWebUrl(getContext(), weburl);
	}

	/**
	 * Set value of WebUrl
	 * @param context
	 * @param weburl
	 */
	public final void setWebUrl(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String weburl)
	{
		getMendixObject().setValue(context, MemberNames.WebUrl.toString(), weburl);
	}

	/**
	 * @return value of BaseItemCreatedBy_BaseItem
	 */
	public final msgraphconnector.proxies.BaseItemCreatedBy getBaseItemCreatedBy_BaseItem() throws com.mendix.core.CoreException
	{
		return getBaseItemCreatedBy_BaseItem(getContext());
	}

	/**
	 * @param context
	 * @return value of BaseItemCreatedBy_BaseItem
	 */
	public final msgraphconnector.proxies.BaseItemCreatedBy getBaseItemCreatedBy_BaseItem(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		msgraphconnector.proxies.BaseItemCreatedBy result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.BaseItemCreatedBy_BaseItem.toString());
		if (identifier != null)
			result = msgraphconnector.proxies.BaseItemCreatedBy.load(context, identifier);
		return result;
	}

	/**
	 * Set value of BaseItemCreatedBy_BaseItem
	 * @param baseitemcreatedby_baseitem
	 */
	public final void setBaseItemCreatedBy_BaseItem(msgraphconnector.proxies.BaseItemCreatedBy baseitemcreatedby_baseitem)
	{
		setBaseItemCreatedBy_BaseItem(getContext(), baseitemcreatedby_baseitem);
	}

	/**
	 * Set value of BaseItemCreatedBy_BaseItem
	 * @param context
	 * @param baseitemcreatedby_baseitem
	 */
	public final void setBaseItemCreatedBy_BaseItem(com.mendix.systemwideinterfaces.core.IContext context, msgraphconnector.proxies.BaseItemCreatedBy baseitemcreatedby_baseitem)
	{
		if (baseitemcreatedby_baseitem == null)
			getMendixObject().setValue(context, MemberNames.BaseItemCreatedBy_BaseItem.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.BaseItemCreatedBy_BaseItem.toString(), baseitemcreatedby_baseitem.getMendixObject().getId());
	}

	/**
	 * @return value of BaseItemLastModifiedBy_BaseItem
	 */
	public final msgraphconnector.proxies.BaseItemLastModifiedBy getBaseItemLastModifiedBy_BaseItem() throws com.mendix.core.CoreException
	{
		return getBaseItemLastModifiedBy_BaseItem(getContext());
	}

	/**
	 * @param context
	 * @return value of BaseItemLastModifiedBy_BaseItem
	 */
	public final msgraphconnector.proxies.BaseItemLastModifiedBy getBaseItemLastModifiedBy_BaseItem(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		msgraphconnector.proxies.BaseItemLastModifiedBy result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.BaseItemLastModifiedBy_BaseItem.toString());
		if (identifier != null)
			result = msgraphconnector.proxies.BaseItemLastModifiedBy.load(context, identifier);
		return result;
	}

	/**
	 * Set value of BaseItemLastModifiedBy_BaseItem
	 * @param baseitemlastmodifiedby_baseitem
	 */
	public final void setBaseItemLastModifiedBy_BaseItem(msgraphconnector.proxies.BaseItemLastModifiedBy baseitemlastmodifiedby_baseitem)
	{
		setBaseItemLastModifiedBy_BaseItem(getContext(), baseitemlastmodifiedby_baseitem);
	}

	/**
	 * Set value of BaseItemLastModifiedBy_BaseItem
	 * @param context
	 * @param baseitemlastmodifiedby_baseitem
	 */
	public final void setBaseItemLastModifiedBy_BaseItem(com.mendix.systemwideinterfaces.core.IContext context, msgraphconnector.proxies.BaseItemLastModifiedBy baseitemlastmodifiedby_baseitem)
	{
		if (baseitemlastmodifiedby_baseitem == null)
			getMendixObject().setValue(context, MemberNames.BaseItemLastModifiedBy_BaseItem.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.BaseItemLastModifiedBy_BaseItem.toString(), baseitemlastmodifiedby_baseitem.getMendixObject().getId());
	}

	/**
	 * @return value of BaseItemParentReference_BaseItem
	 */
	public final msgraphconnector.proxies.BaseItemParentReference getBaseItemParentReference_BaseItem() throws com.mendix.core.CoreException
	{
		return getBaseItemParentReference_BaseItem(getContext());
	}

	/**
	 * @param context
	 * @return value of BaseItemParentReference_BaseItem
	 */
	public final msgraphconnector.proxies.BaseItemParentReference getBaseItemParentReference_BaseItem(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		msgraphconnector.proxies.BaseItemParentReference result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.BaseItemParentReference_BaseItem.toString());
		if (identifier != null)
			result = msgraphconnector.proxies.BaseItemParentReference.load(context, identifier);
		return result;
	}

	/**
	 * Set value of BaseItemParentReference_BaseItem
	 * @param baseitemparentreference_baseitem
	 */
	public final void setBaseItemParentReference_BaseItem(msgraphconnector.proxies.BaseItemParentReference baseitemparentreference_baseitem)
	{
		setBaseItemParentReference_BaseItem(getContext(), baseitemparentreference_baseitem);
	}

	/**
	 * Set value of BaseItemParentReference_BaseItem
	 * @param context
	 * @param baseitemparentreference_baseitem
	 */
	public final void setBaseItemParentReference_BaseItem(com.mendix.systemwideinterfaces.core.IContext context, msgraphconnector.proxies.BaseItemParentReference baseitemparentreference_baseitem)
	{
		if (baseitemparentreference_baseitem == null)
			getMendixObject().setValue(context, MemberNames.BaseItemParentReference_BaseItem.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.BaseItemParentReference_BaseItem.toString(), baseitemparentreference_baseitem.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return baseItemMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final msgraphconnector.proxies.BaseItem that = (msgraphconnector.proxies.BaseItem) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MSGraphConnector.BaseItem";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
