// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package msgraphconnector.proxies;

public class BaseItemIdentity
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject baseItemIdentityMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MSGraphConnector.BaseItemIdentity";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		DisplayName("DisplayName"),
		_id("_id"),
		BaseItemIdentity_Application_BaseItemIdentity("MSGraphConnector.BaseItemIdentity_Application_BaseItemIdentity"),
		BaseItemIdentity_Device_BaseItemIdentity("MSGraphConnector.BaseItemIdentity_Device_BaseItemIdentity"),
		BaseItemIdentity_User_BaseItemIdentity("MSGraphConnector.BaseItemIdentity_User_BaseItemIdentity");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public BaseItemIdentity(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MSGraphConnector.BaseItemIdentity"));
	}

	protected BaseItemIdentity(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject baseItemIdentityMendixObject)
	{
		if (baseItemIdentityMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MSGraphConnector.BaseItemIdentity", baseItemIdentityMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MSGraphConnector.BaseItemIdentity");

		this.baseItemIdentityMendixObject = baseItemIdentityMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'BaseItemIdentity.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static msgraphconnector.proxies.BaseItemIdentity initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return msgraphconnector.proxies.BaseItemIdentity.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static msgraphconnector.proxies.BaseItemIdentity initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new msgraphconnector.proxies.BaseItemIdentity(context, mendixObject);
	}

	public static msgraphconnector.proxies.BaseItemIdentity load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return msgraphconnector.proxies.BaseItemIdentity.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of DisplayName
	 */
	public final java.lang.String getDisplayName()
	{
		return getDisplayName(getContext());
	}

	/**
	 * @param context
	 * @return value of DisplayName
	 */
	public final java.lang.String getDisplayName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.DisplayName.toString());
	}

	/**
	 * Set value of DisplayName
	 * @param displayname
	 */
	public final void setDisplayName(java.lang.String displayname)
	{
		setDisplayName(getContext(), displayname);
	}

	/**
	 * Set value of DisplayName
	 * @param context
	 * @param displayname
	 */
	public final void setDisplayName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String displayname)
	{
		getMendixObject().setValue(context, MemberNames.DisplayName.toString(), displayname);
	}

	/**
	 * @return value of _id
	 */
	public final java.lang.String get_id()
	{
		return get_id(getContext());
	}

	/**
	 * @param context
	 * @return value of _id
	 */
	public final java.lang.String get_id(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames._id.toString());
	}

	/**
	 * Set value of _id
	 * @param _id
	 */
	public final void set_id(java.lang.String _id)
	{
		set_id(getContext(), _id);
	}

	/**
	 * Set value of _id
	 * @param context
	 * @param _id
	 */
	public final void set_id(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String _id)
	{
		getMendixObject().setValue(context, MemberNames._id.toString(), _id);
	}

	/**
	 * @return value of BaseItemIdentity_Application_BaseItemIdentity
	 */
	public final msgraphconnector.proxies.BaseItemIdentitySet getBaseItemIdentity_Application_BaseItemIdentity() throws com.mendix.core.CoreException
	{
		return getBaseItemIdentity_Application_BaseItemIdentity(getContext());
	}

	/**
	 * @param context
	 * @return value of BaseItemIdentity_Application_BaseItemIdentity
	 */
	public final msgraphconnector.proxies.BaseItemIdentitySet getBaseItemIdentity_Application_BaseItemIdentity(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		msgraphconnector.proxies.BaseItemIdentitySet result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.BaseItemIdentity_Application_BaseItemIdentity.toString());
		if (identifier != null)
			result = msgraphconnector.proxies.BaseItemIdentitySet.load(context, identifier);
		return result;
	}

	/**
	 * Set value of BaseItemIdentity_Application_BaseItemIdentity
	 * @param baseitemidentity_application_baseitemidentity
	 */
	public final void setBaseItemIdentity_Application_BaseItemIdentity(msgraphconnector.proxies.BaseItemIdentitySet baseitemidentity_application_baseitemidentity)
	{
		setBaseItemIdentity_Application_BaseItemIdentity(getContext(), baseitemidentity_application_baseitemidentity);
	}

	/**
	 * Set value of BaseItemIdentity_Application_BaseItemIdentity
	 * @param context
	 * @param baseitemidentity_application_baseitemidentity
	 */
	public final void setBaseItemIdentity_Application_BaseItemIdentity(com.mendix.systemwideinterfaces.core.IContext context, msgraphconnector.proxies.BaseItemIdentitySet baseitemidentity_application_baseitemidentity)
	{
		if (baseitemidentity_application_baseitemidentity == null)
			getMendixObject().setValue(context, MemberNames.BaseItemIdentity_Application_BaseItemIdentity.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.BaseItemIdentity_Application_BaseItemIdentity.toString(), baseitemidentity_application_baseitemidentity.getMendixObject().getId());
	}

	/**
	 * @return value of BaseItemIdentity_Device_BaseItemIdentity
	 */
	public final msgraphconnector.proxies.BaseItemIdentitySet getBaseItemIdentity_Device_BaseItemIdentity() throws com.mendix.core.CoreException
	{
		return getBaseItemIdentity_Device_BaseItemIdentity(getContext());
	}

	/**
	 * @param context
	 * @return value of BaseItemIdentity_Device_BaseItemIdentity
	 */
	public final msgraphconnector.proxies.BaseItemIdentitySet getBaseItemIdentity_Device_BaseItemIdentity(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		msgraphconnector.proxies.BaseItemIdentitySet result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.BaseItemIdentity_Device_BaseItemIdentity.toString());
		if (identifier != null)
			result = msgraphconnector.proxies.BaseItemIdentitySet.load(context, identifier);
		return result;
	}

	/**
	 * Set value of BaseItemIdentity_Device_BaseItemIdentity
	 * @param baseitemidentity_device_baseitemidentity
	 */
	public final void setBaseItemIdentity_Device_BaseItemIdentity(msgraphconnector.proxies.BaseItemIdentitySet baseitemidentity_device_baseitemidentity)
	{
		setBaseItemIdentity_Device_BaseItemIdentity(getContext(), baseitemidentity_device_baseitemidentity);
	}

	/**
	 * Set value of BaseItemIdentity_Device_BaseItemIdentity
	 * @param context
	 * @param baseitemidentity_device_baseitemidentity
	 */
	public final void setBaseItemIdentity_Device_BaseItemIdentity(com.mendix.systemwideinterfaces.core.IContext context, msgraphconnector.proxies.BaseItemIdentitySet baseitemidentity_device_baseitemidentity)
	{
		if (baseitemidentity_device_baseitemidentity == null)
			getMendixObject().setValue(context, MemberNames.BaseItemIdentity_Device_BaseItemIdentity.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.BaseItemIdentity_Device_BaseItemIdentity.toString(), baseitemidentity_device_baseitemidentity.getMendixObject().getId());
	}

	/**
	 * @return value of BaseItemIdentity_User_BaseItemIdentity
	 */
	public final msgraphconnector.proxies.BaseItemIdentitySet getBaseItemIdentity_User_BaseItemIdentity() throws com.mendix.core.CoreException
	{
		return getBaseItemIdentity_User_BaseItemIdentity(getContext());
	}

	/**
	 * @param context
	 * @return value of BaseItemIdentity_User_BaseItemIdentity
	 */
	public final msgraphconnector.proxies.BaseItemIdentitySet getBaseItemIdentity_User_BaseItemIdentity(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		msgraphconnector.proxies.BaseItemIdentitySet result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.BaseItemIdentity_User_BaseItemIdentity.toString());
		if (identifier != null)
			result = msgraphconnector.proxies.BaseItemIdentitySet.load(context, identifier);
		return result;
	}

	/**
	 * Set value of BaseItemIdentity_User_BaseItemIdentity
	 * @param baseitemidentity_user_baseitemidentity
	 */
	public final void setBaseItemIdentity_User_BaseItemIdentity(msgraphconnector.proxies.BaseItemIdentitySet baseitemidentity_user_baseitemidentity)
	{
		setBaseItemIdentity_User_BaseItemIdentity(getContext(), baseitemidentity_user_baseitemidentity);
	}

	/**
	 * Set value of BaseItemIdentity_User_BaseItemIdentity
	 * @param context
	 * @param baseitemidentity_user_baseitemidentity
	 */
	public final void setBaseItemIdentity_User_BaseItemIdentity(com.mendix.systemwideinterfaces.core.IContext context, msgraphconnector.proxies.BaseItemIdentitySet baseitemidentity_user_baseitemidentity)
	{
		if (baseitemidentity_user_baseitemidentity == null)
			getMendixObject().setValue(context, MemberNames.BaseItemIdentity_User_BaseItemIdentity.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.BaseItemIdentity_User_BaseItemIdentity.toString(), baseitemidentity_user_baseitemidentity.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return baseItemIdentityMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final msgraphconnector.proxies.BaseItemIdentity that = (msgraphconnector.proxies.BaseItemIdentity) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MSGraphConnector.BaseItemIdentity";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
