// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package msgraphconnector.proxies;

public class MSGraphAuthLog
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject mSGraphAuthLogMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MSGraphConnector.MSGraphAuthLog";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		AccessAttemptOn("AccessAttemptOn"),
		Message("Message"),
		IncomingDataDetail("IncomingDataDetail");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public MSGraphAuthLog(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MSGraphConnector.MSGraphAuthLog"));
	}

	protected MSGraphAuthLog(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mSGraphAuthLogMendixObject)
	{
		if (mSGraphAuthLogMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MSGraphConnector.MSGraphAuthLog", mSGraphAuthLogMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MSGraphConnector.MSGraphAuthLog");

		this.mSGraphAuthLogMendixObject = mSGraphAuthLogMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'MSGraphAuthLog.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static msgraphconnector.proxies.MSGraphAuthLog initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return msgraphconnector.proxies.MSGraphAuthLog.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static msgraphconnector.proxies.MSGraphAuthLog initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new msgraphconnector.proxies.MSGraphAuthLog(context, mendixObject);
	}

	public static msgraphconnector.proxies.MSGraphAuthLog load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return msgraphconnector.proxies.MSGraphAuthLog.initialize(context, mendixObject);
	}

	public static java.util.List<msgraphconnector.proxies.MSGraphAuthLog> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<msgraphconnector.proxies.MSGraphAuthLog> result = new java.util.ArrayList<msgraphconnector.proxies.MSGraphAuthLog>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//MSGraphConnector.MSGraphAuthLog" + xpathConstraint))
			result.add(msgraphconnector.proxies.MSGraphAuthLog.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of AccessAttemptOn
	 */
	public final java.util.Date getAccessAttemptOn()
	{
		return getAccessAttemptOn(getContext());
	}

	/**
	 * @param context
	 * @return value of AccessAttemptOn
	 */
	public final java.util.Date getAccessAttemptOn(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.AccessAttemptOn.toString());
	}

	/**
	 * Set value of AccessAttemptOn
	 * @param accessattempton
	 */
	public final void setAccessAttemptOn(java.util.Date accessattempton)
	{
		setAccessAttemptOn(getContext(), accessattempton);
	}

	/**
	 * Set value of AccessAttemptOn
	 * @param context
	 * @param accessattempton
	 */
	public final void setAccessAttemptOn(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date accessattempton)
	{
		getMendixObject().setValue(context, MemberNames.AccessAttemptOn.toString(), accessattempton);
	}

	/**
	 * Set value of Message
	 * @param message
	 */
	public final msgraphconnector.proxies.MSGraphAuthMessage getMessage()
	{
		return getMessage(getContext());
	}

	/**
	 * @param context
	 * @return value of Message
	 */
	public final msgraphconnector.proxies.MSGraphAuthMessage getMessage(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Message.toString());
		if (obj == null)
			return null;

		return msgraphconnector.proxies.MSGraphAuthMessage.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Message
	 * @param message
	 */
	public final void setMessage(msgraphconnector.proxies.MSGraphAuthMessage message)
	{
		setMessage(getContext(), message);
	}

	/**
	 * Set value of Message
	 * @param context
	 * @param message
	 */
	public final void setMessage(com.mendix.systemwideinterfaces.core.IContext context, msgraphconnector.proxies.MSGraphAuthMessage message)
	{
		if (message != null)
			getMendixObject().setValue(context, MemberNames.Message.toString(), message.toString());
		else
			getMendixObject().setValue(context, MemberNames.Message.toString(), null);
	}

	/**
	 * @return value of IncomingDataDetail
	 */
	public final java.lang.String getIncomingDataDetail()
	{
		return getIncomingDataDetail(getContext());
	}

	/**
	 * @param context
	 * @return value of IncomingDataDetail
	 */
	public final java.lang.String getIncomingDataDetail(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.IncomingDataDetail.toString());
	}

	/**
	 * Set value of IncomingDataDetail
	 * @param incomingdatadetail
	 */
	public final void setIncomingDataDetail(java.lang.String incomingdatadetail)
	{
		setIncomingDataDetail(getContext(), incomingdatadetail);
	}

	/**
	 * Set value of IncomingDataDetail
	 * @param context
	 * @param incomingdatadetail
	 */
	public final void setIncomingDataDetail(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String incomingdatadetail)
	{
		getMendixObject().setValue(context, MemberNames.IncomingDataDetail.toString(), incomingdatadetail);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return mSGraphAuthLogMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final msgraphconnector.proxies.MSGraphAuthLog that = (msgraphconnector.proxies.MSGraphAuthLog) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MSGraphConnector.MSGraphAuthLog";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
