// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package msgraphconnector.proxies;

public class UserProvisionedPlans
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject userProvisionedPlansMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MSGraphConnector.UserProvisionedPlans";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		CapabilityStatus("CapabilityStatus"),
		ProvisioningStatus("ProvisioningStatus"),
		Service("Service"),
		ProvisionedPlans_User("MSGraphConnector.ProvisionedPlans_User");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public UserProvisionedPlans(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MSGraphConnector.UserProvisionedPlans"));
	}

	protected UserProvisionedPlans(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject userProvisionedPlansMendixObject)
	{
		if (userProvisionedPlansMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MSGraphConnector.UserProvisionedPlans", userProvisionedPlansMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MSGraphConnector.UserProvisionedPlans");

		this.userProvisionedPlansMendixObject = userProvisionedPlansMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'UserProvisionedPlans.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static msgraphconnector.proxies.UserProvisionedPlans initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return msgraphconnector.proxies.UserProvisionedPlans.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static msgraphconnector.proxies.UserProvisionedPlans initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new msgraphconnector.proxies.UserProvisionedPlans(context, mendixObject);
	}

	public static msgraphconnector.proxies.UserProvisionedPlans load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return msgraphconnector.proxies.UserProvisionedPlans.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of CapabilityStatus
	 */
	public final java.lang.String getCapabilityStatus()
	{
		return getCapabilityStatus(getContext());
	}

	/**
	 * @param context
	 * @return value of CapabilityStatus
	 */
	public final java.lang.String getCapabilityStatus(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.CapabilityStatus.toString());
	}

	/**
	 * Set value of CapabilityStatus
	 * @param capabilitystatus
	 */
	public final void setCapabilityStatus(java.lang.String capabilitystatus)
	{
		setCapabilityStatus(getContext(), capabilitystatus);
	}

	/**
	 * Set value of CapabilityStatus
	 * @param context
	 * @param capabilitystatus
	 */
	public final void setCapabilityStatus(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String capabilitystatus)
	{
		getMendixObject().setValue(context, MemberNames.CapabilityStatus.toString(), capabilitystatus);
	}

	/**
	 * @return value of ProvisioningStatus
	 */
	public final java.lang.String getProvisioningStatus()
	{
		return getProvisioningStatus(getContext());
	}

	/**
	 * @param context
	 * @return value of ProvisioningStatus
	 */
	public final java.lang.String getProvisioningStatus(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ProvisioningStatus.toString());
	}

	/**
	 * Set value of ProvisioningStatus
	 * @param provisioningstatus
	 */
	public final void setProvisioningStatus(java.lang.String provisioningstatus)
	{
		setProvisioningStatus(getContext(), provisioningstatus);
	}

	/**
	 * Set value of ProvisioningStatus
	 * @param context
	 * @param provisioningstatus
	 */
	public final void setProvisioningStatus(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String provisioningstatus)
	{
		getMendixObject().setValue(context, MemberNames.ProvisioningStatus.toString(), provisioningstatus);
	}

	/**
	 * @return value of Service
	 */
	public final java.lang.String getService()
	{
		return getService(getContext());
	}

	/**
	 * @param context
	 * @return value of Service
	 */
	public final java.lang.String getService(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Service.toString());
	}

	/**
	 * Set value of Service
	 * @param service
	 */
	public final void setService(java.lang.String service)
	{
		setService(getContext(), service);
	}

	/**
	 * Set value of Service
	 * @param context
	 * @param service
	 */
	public final void setService(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String service)
	{
		getMendixObject().setValue(context, MemberNames.Service.toString(), service);
	}

	/**
	 * @return value of ProvisionedPlans_User
	 */
	public final msgraphconnector.proxies.User getProvisionedPlans_User() throws com.mendix.core.CoreException
	{
		return getProvisionedPlans_User(getContext());
	}

	/**
	 * @param context
	 * @return value of ProvisionedPlans_User
	 */
	public final msgraphconnector.proxies.User getProvisionedPlans_User(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		msgraphconnector.proxies.User result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ProvisionedPlans_User.toString());
		if (identifier != null)
			result = msgraphconnector.proxies.User.load(context, identifier);
		return result;
	}

	/**
	 * Set value of ProvisionedPlans_User
	 * @param provisionedplans_user
	 */
	public final void setProvisionedPlans_User(msgraphconnector.proxies.User provisionedplans_user)
	{
		setProvisionedPlans_User(getContext(), provisionedplans_user);
	}

	/**
	 * Set value of ProvisionedPlans_User
	 * @param context
	 * @param provisionedplans_user
	 */
	public final void setProvisionedPlans_User(com.mendix.systemwideinterfaces.core.IContext context, msgraphconnector.proxies.User provisionedplans_user)
	{
		if (provisionedplans_user == null)
			getMendixObject().setValue(context, MemberNames.ProvisionedPlans_User.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.ProvisionedPlans_User.toString(), provisionedplans_user.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return userProvisionedPlansMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final msgraphconnector.proxies.UserProvisionedPlans that = (msgraphconnector.proxies.UserProvisionedPlans) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MSGraphConnector.UserProvisionedPlans";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
