// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package msgraphconnector.proxies;

public class UserDisabledPlans
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject userDisabledPlansMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MSGraphConnector.UserDisabledPlans";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		DisabledPlans_AssignedLicenses("MSGraphConnector.DisabledPlans_AssignedLicenses");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public UserDisabledPlans(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MSGraphConnector.UserDisabledPlans"));
	}

	protected UserDisabledPlans(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject userDisabledPlansMendixObject)
	{
		if (userDisabledPlansMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MSGraphConnector.UserDisabledPlans", userDisabledPlansMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MSGraphConnector.UserDisabledPlans");

		this.userDisabledPlansMendixObject = userDisabledPlansMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'UserDisabledPlans.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static msgraphconnector.proxies.UserDisabledPlans initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return msgraphconnector.proxies.UserDisabledPlans.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static msgraphconnector.proxies.UserDisabledPlans initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new msgraphconnector.proxies.UserDisabledPlans(context, mendixObject);
	}

	public static msgraphconnector.proxies.UserDisabledPlans load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return msgraphconnector.proxies.UserDisabledPlans.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of DisabledPlans_AssignedLicenses
	 */
	public final msgraphconnector.proxies.UserAssignedLicenses getDisabledPlans_AssignedLicenses() throws com.mendix.core.CoreException
	{
		return getDisabledPlans_AssignedLicenses(getContext());
	}

	/**
	 * @param context
	 * @return value of DisabledPlans_AssignedLicenses
	 */
	public final msgraphconnector.proxies.UserAssignedLicenses getDisabledPlans_AssignedLicenses(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		msgraphconnector.proxies.UserAssignedLicenses result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.DisabledPlans_AssignedLicenses.toString());
		if (identifier != null)
			result = msgraphconnector.proxies.UserAssignedLicenses.load(context, identifier);
		return result;
	}

	/**
	 * Set value of DisabledPlans_AssignedLicenses
	 * @param disabledplans_assignedlicenses
	 */
	public final void setDisabledPlans_AssignedLicenses(msgraphconnector.proxies.UserAssignedLicenses disabledplans_assignedlicenses)
	{
		setDisabledPlans_AssignedLicenses(getContext(), disabledplans_assignedlicenses);
	}

	/**
	 * Set value of DisabledPlans_AssignedLicenses
	 * @param context
	 * @param disabledplans_assignedlicenses
	 */
	public final void setDisabledPlans_AssignedLicenses(com.mendix.systemwideinterfaces.core.IContext context, msgraphconnector.proxies.UserAssignedLicenses disabledplans_assignedlicenses)
	{
		if (disabledplans_assignedlicenses == null)
			getMendixObject().setValue(context, MemberNames.DisabledPlans_AssignedLicenses.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.DisabledPlans_AssignedLicenses.toString(), disabledplans_assignedlicenses.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return userDisabledPlansMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final msgraphconnector.proxies.UserDisabledPlans that = (msgraphconnector.proxies.UserDisabledPlans) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MSGraphConnector.UserDisabledPlans";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
