// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package msgraphconnector.proxies;

public class User
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject userMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MSGraphConnector.User";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		_odata_context("_odata_context"),
		AboutMe("AboutMe"),
		AccountEnabled("AccountEnabled"),
		Birthday("Birthday"),
		City("City"),
		CompanyName("CompanyName"),
		Country("Country"),
		Department("Department"),
		DisplayName("DisplayName"),
		GivenName("GivenName"),
		HireDate("HireDate"),
		_id("_id"),
		JobTitle("JobTitle"),
		Mail("Mail"),
		MailNickname("MailNickname"),
		MobilePhone("MobilePhone"),
		MySite("MySite"),
		OfficeLocation("OfficeLocation"),
		OnPremisesImmutableId("OnPremisesImmutableId"),
		OnPremisesLastSyncDateTime("OnPremisesLastSyncDateTime"),
		OnPremisesSecurityIdentifier("OnPremisesSecurityIdentifier"),
		OnPremisesSyncEnabled("OnPremisesSyncEnabled"),
		PasswordPolicies("PasswordPolicies"),
		PostalCode("PostalCode"),
		PreferredLanguage("PreferredLanguage"),
		PreferredName("PreferredName"),
		State("State"),
		StreetAddress("StreetAddress"),
		Surname("Surname"),
		UsageLocation("UsageLocation"),
		UserPrincipalName("UserPrincipalName"),
		UserType("UserType"),
		User_Result("MSGraphConnector.User_Result"),
		BusinessPhones_User("MSGraphConnector.BusinessPhones_User"),
		ImAddresses_User("MSGraphConnector.ImAddresses_User"),
		Interests_User("MSGraphConnector.Interests_User"),
		MailboxSettings_User("MSGraphConnector.MailboxSettings_User"),
		PasswordProfile_User("MSGraphConnector.PasswordProfile_User"),
		PastProjects_User("MSGraphConnector.PastProjects_User"),
		ProxyAddresses_User("MSGraphConnector.ProxyAddresses_User"),
		Responsibilities_User("MSGraphConnector.Responsibilities_User"),
		Schools_User("MSGraphConnector.Schools_User"),
		Skills_User("MSGraphConnector.Skills_User");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public User(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MSGraphConnector.User"));
	}

	protected User(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject userMendixObject)
	{
		if (userMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MSGraphConnector.User", userMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MSGraphConnector.User");

		this.userMendixObject = userMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'User.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static msgraphconnector.proxies.User initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return msgraphconnector.proxies.User.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static msgraphconnector.proxies.User initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new msgraphconnector.proxies.User(context, mendixObject);
	}

	public static msgraphconnector.proxies.User load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return msgraphconnector.proxies.User.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of _odata_context
	 */
	public final java.lang.String get_odata_context()
	{
		return get_odata_context(getContext());
	}

	/**
	 * @param context
	 * @return value of _odata_context
	 */
	public final java.lang.String get_odata_context(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames._odata_context.toString());
	}

	/**
	 * Set value of _odata_context
	 * @param _odata_context
	 */
	public final void set_odata_context(java.lang.String _odata_context)
	{
		set_odata_context(getContext(), _odata_context);
	}

	/**
	 * Set value of _odata_context
	 * @param context
	 * @param _odata_context
	 */
	public final void set_odata_context(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String _odata_context)
	{
		getMendixObject().setValue(context, MemberNames._odata_context.toString(), _odata_context);
	}

	/**
	 * @return value of AboutMe
	 */
	public final java.lang.String getAboutMe()
	{
		return getAboutMe(getContext());
	}

	/**
	 * @param context
	 * @return value of AboutMe
	 */
	public final java.lang.String getAboutMe(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.AboutMe.toString());
	}

	/**
	 * Set value of AboutMe
	 * @param aboutme
	 */
	public final void setAboutMe(java.lang.String aboutme)
	{
		setAboutMe(getContext(), aboutme);
	}

	/**
	 * Set value of AboutMe
	 * @param context
	 * @param aboutme
	 */
	public final void setAboutMe(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String aboutme)
	{
		getMendixObject().setValue(context, MemberNames.AboutMe.toString(), aboutme);
	}

	/**
	 * @return value of AccountEnabled
	 */
	public final java.lang.Boolean getAccountEnabled()
	{
		return getAccountEnabled(getContext());
	}

	/**
	 * @param context
	 * @return value of AccountEnabled
	 */
	public final java.lang.Boolean getAccountEnabled(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.AccountEnabled.toString());
	}

	/**
	 * Set value of AccountEnabled
	 * @param accountenabled
	 */
	public final void setAccountEnabled(java.lang.Boolean accountenabled)
	{
		setAccountEnabled(getContext(), accountenabled);
	}

	/**
	 * Set value of AccountEnabled
	 * @param context
	 * @param accountenabled
	 */
	public final void setAccountEnabled(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean accountenabled)
	{
		getMendixObject().setValue(context, MemberNames.AccountEnabled.toString(), accountenabled);
	}

	/**
	 * @return value of Birthday
	 */
	public final java.util.Date getBirthday()
	{
		return getBirthday(getContext());
	}

	/**
	 * @param context
	 * @return value of Birthday
	 */
	public final java.util.Date getBirthday(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.Birthday.toString());
	}

	/**
	 * Set value of Birthday
	 * @param birthday
	 */
	public final void setBirthday(java.util.Date birthday)
	{
		setBirthday(getContext(), birthday);
	}

	/**
	 * Set value of Birthday
	 * @param context
	 * @param birthday
	 */
	public final void setBirthday(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date birthday)
	{
		getMendixObject().setValue(context, MemberNames.Birthday.toString(), birthday);
	}

	/**
	 * @return value of City
	 */
	public final java.lang.String getCity()
	{
		return getCity(getContext());
	}

	/**
	 * @param context
	 * @return value of City
	 */
	public final java.lang.String getCity(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.City.toString());
	}

	/**
	 * Set value of City
	 * @param city
	 */
	public final void setCity(java.lang.String city)
	{
		setCity(getContext(), city);
	}

	/**
	 * Set value of City
	 * @param context
	 * @param city
	 */
	public final void setCity(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String city)
	{
		getMendixObject().setValue(context, MemberNames.City.toString(), city);
	}

	/**
	 * @return value of CompanyName
	 */
	public final java.lang.String getCompanyName()
	{
		return getCompanyName(getContext());
	}

	/**
	 * @param context
	 * @return value of CompanyName
	 */
	public final java.lang.String getCompanyName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.CompanyName.toString());
	}

	/**
	 * Set value of CompanyName
	 * @param companyname
	 */
	public final void setCompanyName(java.lang.String companyname)
	{
		setCompanyName(getContext(), companyname);
	}

	/**
	 * Set value of CompanyName
	 * @param context
	 * @param companyname
	 */
	public final void setCompanyName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String companyname)
	{
		getMendixObject().setValue(context, MemberNames.CompanyName.toString(), companyname);
	}

	/**
	 * @return value of Country
	 */
	public final java.lang.String getCountry()
	{
		return getCountry(getContext());
	}

	/**
	 * @param context
	 * @return value of Country
	 */
	public final java.lang.String getCountry(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Country.toString());
	}

	/**
	 * Set value of Country
	 * @param country
	 */
	public final void setCountry(java.lang.String country)
	{
		setCountry(getContext(), country);
	}

	/**
	 * Set value of Country
	 * @param context
	 * @param country
	 */
	public final void setCountry(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String country)
	{
		getMendixObject().setValue(context, MemberNames.Country.toString(), country);
	}

	/**
	 * @return value of Department
	 */
	public final java.lang.String getDepartment()
	{
		return getDepartment(getContext());
	}

	/**
	 * @param context
	 * @return value of Department
	 */
	public final java.lang.String getDepartment(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Department.toString());
	}

	/**
	 * Set value of Department
	 * @param department
	 */
	public final void setDepartment(java.lang.String department)
	{
		setDepartment(getContext(), department);
	}

	/**
	 * Set value of Department
	 * @param context
	 * @param department
	 */
	public final void setDepartment(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String department)
	{
		getMendixObject().setValue(context, MemberNames.Department.toString(), department);
	}

	/**
	 * @return value of DisplayName
	 */
	public final java.lang.String getDisplayName()
	{
		return getDisplayName(getContext());
	}

	/**
	 * @param context
	 * @return value of DisplayName
	 */
	public final java.lang.String getDisplayName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.DisplayName.toString());
	}

	/**
	 * Set value of DisplayName
	 * @param displayname
	 */
	public final void setDisplayName(java.lang.String displayname)
	{
		setDisplayName(getContext(), displayname);
	}

	/**
	 * Set value of DisplayName
	 * @param context
	 * @param displayname
	 */
	public final void setDisplayName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String displayname)
	{
		getMendixObject().setValue(context, MemberNames.DisplayName.toString(), displayname);
	}

	/**
	 * @return value of GivenName
	 */
	public final java.lang.String getGivenName()
	{
		return getGivenName(getContext());
	}

	/**
	 * @param context
	 * @return value of GivenName
	 */
	public final java.lang.String getGivenName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.GivenName.toString());
	}

	/**
	 * Set value of GivenName
	 * @param givenname
	 */
	public final void setGivenName(java.lang.String givenname)
	{
		setGivenName(getContext(), givenname);
	}

	/**
	 * Set value of GivenName
	 * @param context
	 * @param givenname
	 */
	public final void setGivenName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String givenname)
	{
		getMendixObject().setValue(context, MemberNames.GivenName.toString(), givenname);
	}

	/**
	 * @return value of HireDate
	 */
	public final java.util.Date getHireDate()
	{
		return getHireDate(getContext());
	}

	/**
	 * @param context
	 * @return value of HireDate
	 */
	public final java.util.Date getHireDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.HireDate.toString());
	}

	/**
	 * Set value of HireDate
	 * @param hiredate
	 */
	public final void setHireDate(java.util.Date hiredate)
	{
		setHireDate(getContext(), hiredate);
	}

	/**
	 * Set value of HireDate
	 * @param context
	 * @param hiredate
	 */
	public final void setHireDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date hiredate)
	{
		getMendixObject().setValue(context, MemberNames.HireDate.toString(), hiredate);
	}

	/**
	 * @return value of _id
	 */
	public final java.lang.String get_id()
	{
		return get_id(getContext());
	}

	/**
	 * @param context
	 * @return value of _id
	 */
	public final java.lang.String get_id(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames._id.toString());
	}

	/**
	 * Set value of _id
	 * @param _id
	 */
	public final void set_id(java.lang.String _id)
	{
		set_id(getContext(), _id);
	}

	/**
	 * Set value of _id
	 * @param context
	 * @param _id
	 */
	public final void set_id(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String _id)
	{
		getMendixObject().setValue(context, MemberNames._id.toString(), _id);
	}

	/**
	 * @return value of JobTitle
	 */
	public final java.lang.String getJobTitle()
	{
		return getJobTitle(getContext());
	}

	/**
	 * @param context
	 * @return value of JobTitle
	 */
	public final java.lang.String getJobTitle(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.JobTitle.toString());
	}

	/**
	 * Set value of JobTitle
	 * @param jobtitle
	 */
	public final void setJobTitle(java.lang.String jobtitle)
	{
		setJobTitle(getContext(), jobtitle);
	}

	/**
	 * Set value of JobTitle
	 * @param context
	 * @param jobtitle
	 */
	public final void setJobTitle(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String jobtitle)
	{
		getMendixObject().setValue(context, MemberNames.JobTitle.toString(), jobtitle);
	}

	/**
	 * @return value of Mail
	 */
	public final java.lang.String getMail()
	{
		return getMail(getContext());
	}

	/**
	 * @param context
	 * @return value of Mail
	 */
	public final java.lang.String getMail(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Mail.toString());
	}

	/**
	 * Set value of Mail
	 * @param mail
	 */
	public final void setMail(java.lang.String mail)
	{
		setMail(getContext(), mail);
	}

	/**
	 * Set value of Mail
	 * @param context
	 * @param mail
	 */
	public final void setMail(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String mail)
	{
		getMendixObject().setValue(context, MemberNames.Mail.toString(), mail);
	}

	/**
	 * @return value of MailNickname
	 */
	public final java.lang.String getMailNickname()
	{
		return getMailNickname(getContext());
	}

	/**
	 * @param context
	 * @return value of MailNickname
	 */
	public final java.lang.String getMailNickname(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MailNickname.toString());
	}

	/**
	 * Set value of MailNickname
	 * @param mailnickname
	 */
	public final void setMailNickname(java.lang.String mailnickname)
	{
		setMailNickname(getContext(), mailnickname);
	}

	/**
	 * Set value of MailNickname
	 * @param context
	 * @param mailnickname
	 */
	public final void setMailNickname(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String mailnickname)
	{
		getMendixObject().setValue(context, MemberNames.MailNickname.toString(), mailnickname);
	}

	/**
	 * @return value of MobilePhone
	 */
	public final java.lang.String getMobilePhone()
	{
		return getMobilePhone(getContext());
	}

	/**
	 * @param context
	 * @return value of MobilePhone
	 */
	public final java.lang.String getMobilePhone(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MobilePhone.toString());
	}

	/**
	 * Set value of MobilePhone
	 * @param mobilephone
	 */
	public final void setMobilePhone(java.lang.String mobilephone)
	{
		setMobilePhone(getContext(), mobilephone);
	}

	/**
	 * Set value of MobilePhone
	 * @param context
	 * @param mobilephone
	 */
	public final void setMobilePhone(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String mobilephone)
	{
		getMendixObject().setValue(context, MemberNames.MobilePhone.toString(), mobilephone);
	}

	/**
	 * @return value of MySite
	 */
	public final java.lang.String getMySite()
	{
		return getMySite(getContext());
	}

	/**
	 * @param context
	 * @return value of MySite
	 */
	public final java.lang.String getMySite(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MySite.toString());
	}

	/**
	 * Set value of MySite
	 * @param mysite
	 */
	public final void setMySite(java.lang.String mysite)
	{
		setMySite(getContext(), mysite);
	}

	/**
	 * Set value of MySite
	 * @param context
	 * @param mysite
	 */
	public final void setMySite(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String mysite)
	{
		getMendixObject().setValue(context, MemberNames.MySite.toString(), mysite);
	}

	/**
	 * @return value of OfficeLocation
	 */
	public final java.lang.String getOfficeLocation()
	{
		return getOfficeLocation(getContext());
	}

	/**
	 * @param context
	 * @return value of OfficeLocation
	 */
	public final java.lang.String getOfficeLocation(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.OfficeLocation.toString());
	}

	/**
	 * Set value of OfficeLocation
	 * @param officelocation
	 */
	public final void setOfficeLocation(java.lang.String officelocation)
	{
		setOfficeLocation(getContext(), officelocation);
	}

	/**
	 * Set value of OfficeLocation
	 * @param context
	 * @param officelocation
	 */
	public final void setOfficeLocation(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String officelocation)
	{
		getMendixObject().setValue(context, MemberNames.OfficeLocation.toString(), officelocation);
	}

	/**
	 * @return value of OnPremisesImmutableId
	 */
	public final java.lang.String getOnPremisesImmutableId()
	{
		return getOnPremisesImmutableId(getContext());
	}

	/**
	 * @param context
	 * @return value of OnPremisesImmutableId
	 */
	public final java.lang.String getOnPremisesImmutableId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.OnPremisesImmutableId.toString());
	}

	/**
	 * Set value of OnPremisesImmutableId
	 * @param onpremisesimmutableid
	 */
	public final void setOnPremisesImmutableId(java.lang.String onpremisesimmutableid)
	{
		setOnPremisesImmutableId(getContext(), onpremisesimmutableid);
	}

	/**
	 * Set value of OnPremisesImmutableId
	 * @param context
	 * @param onpremisesimmutableid
	 */
	public final void setOnPremisesImmutableId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String onpremisesimmutableid)
	{
		getMendixObject().setValue(context, MemberNames.OnPremisesImmutableId.toString(), onpremisesimmutableid);
	}

	/**
	 * @return value of OnPremisesLastSyncDateTime
	 */
	public final java.util.Date getOnPremisesLastSyncDateTime()
	{
		return getOnPremisesLastSyncDateTime(getContext());
	}

	/**
	 * @param context
	 * @return value of OnPremisesLastSyncDateTime
	 */
	public final java.util.Date getOnPremisesLastSyncDateTime(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.OnPremisesLastSyncDateTime.toString());
	}

	/**
	 * Set value of OnPremisesLastSyncDateTime
	 * @param onpremiseslastsyncdatetime
	 */
	public final void setOnPremisesLastSyncDateTime(java.util.Date onpremiseslastsyncdatetime)
	{
		setOnPremisesLastSyncDateTime(getContext(), onpremiseslastsyncdatetime);
	}

	/**
	 * Set value of OnPremisesLastSyncDateTime
	 * @param context
	 * @param onpremiseslastsyncdatetime
	 */
	public final void setOnPremisesLastSyncDateTime(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date onpremiseslastsyncdatetime)
	{
		getMendixObject().setValue(context, MemberNames.OnPremisesLastSyncDateTime.toString(), onpremiseslastsyncdatetime);
	}

	/**
	 * @return value of OnPremisesSecurityIdentifier
	 */
	public final java.lang.String getOnPremisesSecurityIdentifier()
	{
		return getOnPremisesSecurityIdentifier(getContext());
	}

	/**
	 * @param context
	 * @return value of OnPremisesSecurityIdentifier
	 */
	public final java.lang.String getOnPremisesSecurityIdentifier(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.OnPremisesSecurityIdentifier.toString());
	}

	/**
	 * Set value of OnPremisesSecurityIdentifier
	 * @param onpremisessecurityidentifier
	 */
	public final void setOnPremisesSecurityIdentifier(java.lang.String onpremisessecurityidentifier)
	{
		setOnPremisesSecurityIdentifier(getContext(), onpremisessecurityidentifier);
	}

	/**
	 * Set value of OnPremisesSecurityIdentifier
	 * @param context
	 * @param onpremisessecurityidentifier
	 */
	public final void setOnPremisesSecurityIdentifier(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String onpremisessecurityidentifier)
	{
		getMendixObject().setValue(context, MemberNames.OnPremisesSecurityIdentifier.toString(), onpremisessecurityidentifier);
	}

	/**
	 * @return value of OnPremisesSyncEnabled
	 */
	public final java.lang.Boolean getOnPremisesSyncEnabled()
	{
		return getOnPremisesSyncEnabled(getContext());
	}

	/**
	 * @param context
	 * @return value of OnPremisesSyncEnabled
	 */
	public final java.lang.Boolean getOnPremisesSyncEnabled(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.OnPremisesSyncEnabled.toString());
	}

	/**
	 * Set value of OnPremisesSyncEnabled
	 * @param onpremisessyncenabled
	 */
	public final void setOnPremisesSyncEnabled(java.lang.Boolean onpremisessyncenabled)
	{
		setOnPremisesSyncEnabled(getContext(), onpremisessyncenabled);
	}

	/**
	 * Set value of OnPremisesSyncEnabled
	 * @param context
	 * @param onpremisessyncenabled
	 */
	public final void setOnPremisesSyncEnabled(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean onpremisessyncenabled)
	{
		getMendixObject().setValue(context, MemberNames.OnPremisesSyncEnabled.toString(), onpremisessyncenabled);
	}

	/**
	 * @return value of PasswordPolicies
	 */
	public final java.lang.String getPasswordPolicies()
	{
		return getPasswordPolicies(getContext());
	}

	/**
	 * @param context
	 * @return value of PasswordPolicies
	 */
	public final java.lang.String getPasswordPolicies(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.PasswordPolicies.toString());
	}

	/**
	 * Set value of PasswordPolicies
	 * @param passwordpolicies
	 */
	public final void setPasswordPolicies(java.lang.String passwordpolicies)
	{
		setPasswordPolicies(getContext(), passwordpolicies);
	}

	/**
	 * Set value of PasswordPolicies
	 * @param context
	 * @param passwordpolicies
	 */
	public final void setPasswordPolicies(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String passwordpolicies)
	{
		getMendixObject().setValue(context, MemberNames.PasswordPolicies.toString(), passwordpolicies);
	}

	/**
	 * @return value of PostalCode
	 */
	public final java.lang.String getPostalCode()
	{
		return getPostalCode(getContext());
	}

	/**
	 * @param context
	 * @return value of PostalCode
	 */
	public final java.lang.String getPostalCode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.PostalCode.toString());
	}

	/**
	 * Set value of PostalCode
	 * @param postalcode
	 */
	public final void setPostalCode(java.lang.String postalcode)
	{
		setPostalCode(getContext(), postalcode);
	}

	/**
	 * Set value of PostalCode
	 * @param context
	 * @param postalcode
	 */
	public final void setPostalCode(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String postalcode)
	{
		getMendixObject().setValue(context, MemberNames.PostalCode.toString(), postalcode);
	}

	/**
	 * @return value of PreferredLanguage
	 */
	public final java.lang.String getPreferredLanguage()
	{
		return getPreferredLanguage(getContext());
	}

	/**
	 * @param context
	 * @return value of PreferredLanguage
	 */
	public final java.lang.String getPreferredLanguage(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.PreferredLanguage.toString());
	}

	/**
	 * Set value of PreferredLanguage
	 * @param preferredlanguage
	 */
	public final void setPreferredLanguage(java.lang.String preferredlanguage)
	{
		setPreferredLanguage(getContext(), preferredlanguage);
	}

	/**
	 * Set value of PreferredLanguage
	 * @param context
	 * @param preferredlanguage
	 */
	public final void setPreferredLanguage(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String preferredlanguage)
	{
		getMendixObject().setValue(context, MemberNames.PreferredLanguage.toString(), preferredlanguage);
	}

	/**
	 * @return value of PreferredName
	 */
	public final java.lang.String getPreferredName()
	{
		return getPreferredName(getContext());
	}

	/**
	 * @param context
	 * @return value of PreferredName
	 */
	public final java.lang.String getPreferredName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.PreferredName.toString());
	}

	/**
	 * Set value of PreferredName
	 * @param preferredname
	 */
	public final void setPreferredName(java.lang.String preferredname)
	{
		setPreferredName(getContext(), preferredname);
	}

	/**
	 * Set value of PreferredName
	 * @param context
	 * @param preferredname
	 */
	public final void setPreferredName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String preferredname)
	{
		getMendixObject().setValue(context, MemberNames.PreferredName.toString(), preferredname);
	}

	/**
	 * @return value of State
	 */
	public final java.lang.String getState()
	{
		return getState(getContext());
	}

	/**
	 * @param context
	 * @return value of State
	 */
	public final java.lang.String getState(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.State.toString());
	}

	/**
	 * Set value of State
	 * @param state
	 */
	public final void setState(java.lang.String state)
	{
		setState(getContext(), state);
	}

	/**
	 * Set value of State
	 * @param context
	 * @param state
	 */
	public final void setState(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String state)
	{
		getMendixObject().setValue(context, MemberNames.State.toString(), state);
	}

	/**
	 * @return value of StreetAddress
	 */
	public final java.lang.String getStreetAddress()
	{
		return getStreetAddress(getContext());
	}

	/**
	 * @param context
	 * @return value of StreetAddress
	 */
	public final java.lang.String getStreetAddress(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.StreetAddress.toString());
	}

	/**
	 * Set value of StreetAddress
	 * @param streetaddress
	 */
	public final void setStreetAddress(java.lang.String streetaddress)
	{
		setStreetAddress(getContext(), streetaddress);
	}

	/**
	 * Set value of StreetAddress
	 * @param context
	 * @param streetaddress
	 */
	public final void setStreetAddress(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String streetaddress)
	{
		getMendixObject().setValue(context, MemberNames.StreetAddress.toString(), streetaddress);
	}

	/**
	 * @return value of Surname
	 */
	public final java.lang.String getSurname()
	{
		return getSurname(getContext());
	}

	/**
	 * @param context
	 * @return value of Surname
	 */
	public final java.lang.String getSurname(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Surname.toString());
	}

	/**
	 * Set value of Surname
	 * @param surname
	 */
	public final void setSurname(java.lang.String surname)
	{
		setSurname(getContext(), surname);
	}

	/**
	 * Set value of Surname
	 * @param context
	 * @param surname
	 */
	public final void setSurname(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String surname)
	{
		getMendixObject().setValue(context, MemberNames.Surname.toString(), surname);
	}

	/**
	 * @return value of UsageLocation
	 */
	public final java.lang.String getUsageLocation()
	{
		return getUsageLocation(getContext());
	}

	/**
	 * @param context
	 * @return value of UsageLocation
	 */
	public final java.lang.String getUsageLocation(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.UsageLocation.toString());
	}

	/**
	 * Set value of UsageLocation
	 * @param usagelocation
	 */
	public final void setUsageLocation(java.lang.String usagelocation)
	{
		setUsageLocation(getContext(), usagelocation);
	}

	/**
	 * Set value of UsageLocation
	 * @param context
	 * @param usagelocation
	 */
	public final void setUsageLocation(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String usagelocation)
	{
		getMendixObject().setValue(context, MemberNames.UsageLocation.toString(), usagelocation);
	}

	/**
	 * @return value of UserPrincipalName
	 */
	public final java.lang.String getUserPrincipalName()
	{
		return getUserPrincipalName(getContext());
	}

	/**
	 * @param context
	 * @return value of UserPrincipalName
	 */
	public final java.lang.String getUserPrincipalName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.UserPrincipalName.toString());
	}

	/**
	 * Set value of UserPrincipalName
	 * @param userprincipalname
	 */
	public final void setUserPrincipalName(java.lang.String userprincipalname)
	{
		setUserPrincipalName(getContext(), userprincipalname);
	}

	/**
	 * Set value of UserPrincipalName
	 * @param context
	 * @param userprincipalname
	 */
	public final void setUserPrincipalName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String userprincipalname)
	{
		getMendixObject().setValue(context, MemberNames.UserPrincipalName.toString(), userprincipalname);
	}

	/**
	 * @return value of UserType
	 */
	public final java.lang.String getUserType()
	{
		return getUserType(getContext());
	}

	/**
	 * @param context
	 * @return value of UserType
	 */
	public final java.lang.String getUserType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.UserType.toString());
	}

	/**
	 * Set value of UserType
	 * @param usertype
	 */
	public final void setUserType(java.lang.String usertype)
	{
		setUserType(getContext(), usertype);
	}

	/**
	 * Set value of UserType
	 * @param context
	 * @param usertype
	 */
	public final void setUserType(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String usertype)
	{
		getMendixObject().setValue(context, MemberNames.UserType.toString(), usertype);
	}

	/**
	 * @return value of User_Result
	 */
	public final msgraphconnector.proxies.Result getUser_Result() throws com.mendix.core.CoreException
	{
		return getUser_Result(getContext());
	}

	/**
	 * @param context
	 * @return value of User_Result
	 */
	public final msgraphconnector.proxies.Result getUser_Result(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		msgraphconnector.proxies.Result result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.User_Result.toString());
		if (identifier != null)
			result = msgraphconnector.proxies.Result.load(context, identifier);
		return result;
	}

	/**
	 * Set value of User_Result
	 * @param user_result
	 */
	public final void setUser_Result(msgraphconnector.proxies.Result user_result)
	{
		setUser_Result(getContext(), user_result);
	}

	/**
	 * Set value of User_Result
	 * @param context
	 * @param user_result
	 */
	public final void setUser_Result(com.mendix.systemwideinterfaces.core.IContext context, msgraphconnector.proxies.Result user_result)
	{
		if (user_result == null)
			getMendixObject().setValue(context, MemberNames.User_Result.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.User_Result.toString(), user_result.getMendixObject().getId());
	}

	/**
	 * @return value of BusinessPhones_User
	 */
	public final msgraphconnector.proxies.UserBusinessPhones getBusinessPhones_User() throws com.mendix.core.CoreException
	{
		return getBusinessPhones_User(getContext());
	}

	/**
	 * @param context
	 * @return value of BusinessPhones_User
	 */
	public final msgraphconnector.proxies.UserBusinessPhones getBusinessPhones_User(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		msgraphconnector.proxies.UserBusinessPhones result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.BusinessPhones_User.toString());
		if (identifier != null)
			result = msgraphconnector.proxies.UserBusinessPhones.load(context, identifier);
		return result;
	}

	/**
	 * Set value of BusinessPhones_User
	 * @param businessphones_user
	 */
	public final void setBusinessPhones_User(msgraphconnector.proxies.UserBusinessPhones businessphones_user)
	{
		setBusinessPhones_User(getContext(), businessphones_user);
	}

	/**
	 * Set value of BusinessPhones_User
	 * @param context
	 * @param businessphones_user
	 */
	public final void setBusinessPhones_User(com.mendix.systemwideinterfaces.core.IContext context, msgraphconnector.proxies.UserBusinessPhones businessphones_user)
	{
		if (businessphones_user == null)
			getMendixObject().setValue(context, MemberNames.BusinessPhones_User.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.BusinessPhones_User.toString(), businessphones_user.getMendixObject().getId());
	}

	/**
	 * @return value of ImAddresses_User
	 */
	public final msgraphconnector.proxies.UserImAddresses getImAddresses_User() throws com.mendix.core.CoreException
	{
		return getImAddresses_User(getContext());
	}

	/**
	 * @param context
	 * @return value of ImAddresses_User
	 */
	public final msgraphconnector.proxies.UserImAddresses getImAddresses_User(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		msgraphconnector.proxies.UserImAddresses result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ImAddresses_User.toString());
		if (identifier != null)
			result = msgraphconnector.proxies.UserImAddresses.load(context, identifier);
		return result;
	}

	/**
	 * Set value of ImAddresses_User
	 * @param imaddresses_user
	 */
	public final void setImAddresses_User(msgraphconnector.proxies.UserImAddresses imaddresses_user)
	{
		setImAddresses_User(getContext(), imaddresses_user);
	}

	/**
	 * Set value of ImAddresses_User
	 * @param context
	 * @param imaddresses_user
	 */
	public final void setImAddresses_User(com.mendix.systemwideinterfaces.core.IContext context, msgraphconnector.proxies.UserImAddresses imaddresses_user)
	{
		if (imaddresses_user == null)
			getMendixObject().setValue(context, MemberNames.ImAddresses_User.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.ImAddresses_User.toString(), imaddresses_user.getMendixObject().getId());
	}

	/**
	 * @return value of Interests_User
	 */
	public final msgraphconnector.proxies.UserInterests getInterests_User() throws com.mendix.core.CoreException
	{
		return getInterests_User(getContext());
	}

	/**
	 * @param context
	 * @return value of Interests_User
	 */
	public final msgraphconnector.proxies.UserInterests getInterests_User(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		msgraphconnector.proxies.UserInterests result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Interests_User.toString());
		if (identifier != null)
			result = msgraphconnector.proxies.UserInterests.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Interests_User
	 * @param interests_user
	 */
	public final void setInterests_User(msgraphconnector.proxies.UserInterests interests_user)
	{
		setInterests_User(getContext(), interests_user);
	}

	/**
	 * Set value of Interests_User
	 * @param context
	 * @param interests_user
	 */
	public final void setInterests_User(com.mendix.systemwideinterfaces.core.IContext context, msgraphconnector.proxies.UserInterests interests_user)
	{
		if (interests_user == null)
			getMendixObject().setValue(context, MemberNames.Interests_User.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Interests_User.toString(), interests_user.getMendixObject().getId());
	}

	/**
	 * @return value of MailboxSettings_User
	 */
	public final msgraphconnector.proxies.UserMailboxSettings getMailboxSettings_User() throws com.mendix.core.CoreException
	{
		return getMailboxSettings_User(getContext());
	}

	/**
	 * @param context
	 * @return value of MailboxSettings_User
	 */
	public final msgraphconnector.proxies.UserMailboxSettings getMailboxSettings_User(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		msgraphconnector.proxies.UserMailboxSettings result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.MailboxSettings_User.toString());
		if (identifier != null)
			result = msgraphconnector.proxies.UserMailboxSettings.load(context, identifier);
		return result;
	}

	/**
	 * Set value of MailboxSettings_User
	 * @param mailboxsettings_user
	 */
	public final void setMailboxSettings_User(msgraphconnector.proxies.UserMailboxSettings mailboxsettings_user)
	{
		setMailboxSettings_User(getContext(), mailboxsettings_user);
	}

	/**
	 * Set value of MailboxSettings_User
	 * @param context
	 * @param mailboxsettings_user
	 */
	public final void setMailboxSettings_User(com.mendix.systemwideinterfaces.core.IContext context, msgraphconnector.proxies.UserMailboxSettings mailboxsettings_user)
	{
		if (mailboxsettings_user == null)
			getMendixObject().setValue(context, MemberNames.MailboxSettings_User.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.MailboxSettings_User.toString(), mailboxsettings_user.getMendixObject().getId());
	}

	/**
	 * @return value of PasswordProfile_User
	 */
	public final msgraphconnector.proxies.UserPasswordProfile getPasswordProfile_User() throws com.mendix.core.CoreException
	{
		return getPasswordProfile_User(getContext());
	}

	/**
	 * @param context
	 * @return value of PasswordProfile_User
	 */
	public final msgraphconnector.proxies.UserPasswordProfile getPasswordProfile_User(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		msgraphconnector.proxies.UserPasswordProfile result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.PasswordProfile_User.toString());
		if (identifier != null)
			result = msgraphconnector.proxies.UserPasswordProfile.load(context, identifier);
		return result;
	}

	/**
	 * Set value of PasswordProfile_User
	 * @param passwordprofile_user
	 */
	public final void setPasswordProfile_User(msgraphconnector.proxies.UserPasswordProfile passwordprofile_user)
	{
		setPasswordProfile_User(getContext(), passwordprofile_user);
	}

	/**
	 * Set value of PasswordProfile_User
	 * @param context
	 * @param passwordprofile_user
	 */
	public final void setPasswordProfile_User(com.mendix.systemwideinterfaces.core.IContext context, msgraphconnector.proxies.UserPasswordProfile passwordprofile_user)
	{
		if (passwordprofile_user == null)
			getMendixObject().setValue(context, MemberNames.PasswordProfile_User.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.PasswordProfile_User.toString(), passwordprofile_user.getMendixObject().getId());
	}

	/**
	 * @return value of PastProjects_User
	 */
	public final msgraphconnector.proxies.UserPastProjects getPastProjects_User() throws com.mendix.core.CoreException
	{
		return getPastProjects_User(getContext());
	}

	/**
	 * @param context
	 * @return value of PastProjects_User
	 */
	public final msgraphconnector.proxies.UserPastProjects getPastProjects_User(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		msgraphconnector.proxies.UserPastProjects result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.PastProjects_User.toString());
		if (identifier != null)
			result = msgraphconnector.proxies.UserPastProjects.load(context, identifier);
		return result;
	}

	/**
	 * Set value of PastProjects_User
	 * @param pastprojects_user
	 */
	public final void setPastProjects_User(msgraphconnector.proxies.UserPastProjects pastprojects_user)
	{
		setPastProjects_User(getContext(), pastprojects_user);
	}

	/**
	 * Set value of PastProjects_User
	 * @param context
	 * @param pastprojects_user
	 */
	public final void setPastProjects_User(com.mendix.systemwideinterfaces.core.IContext context, msgraphconnector.proxies.UserPastProjects pastprojects_user)
	{
		if (pastprojects_user == null)
			getMendixObject().setValue(context, MemberNames.PastProjects_User.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.PastProjects_User.toString(), pastprojects_user.getMendixObject().getId());
	}

	/**
	 * @return value of ProxyAddresses_User
	 */
	public final msgraphconnector.proxies.UserProxyAddresses getProxyAddresses_User() throws com.mendix.core.CoreException
	{
		return getProxyAddresses_User(getContext());
	}

	/**
	 * @param context
	 * @return value of ProxyAddresses_User
	 */
	public final msgraphconnector.proxies.UserProxyAddresses getProxyAddresses_User(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		msgraphconnector.proxies.UserProxyAddresses result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ProxyAddresses_User.toString());
		if (identifier != null)
			result = msgraphconnector.proxies.UserProxyAddresses.load(context, identifier);
		return result;
	}

	/**
	 * Set value of ProxyAddresses_User
	 * @param proxyaddresses_user
	 */
	public final void setProxyAddresses_User(msgraphconnector.proxies.UserProxyAddresses proxyaddresses_user)
	{
		setProxyAddresses_User(getContext(), proxyaddresses_user);
	}

	/**
	 * Set value of ProxyAddresses_User
	 * @param context
	 * @param proxyaddresses_user
	 */
	public final void setProxyAddresses_User(com.mendix.systemwideinterfaces.core.IContext context, msgraphconnector.proxies.UserProxyAddresses proxyaddresses_user)
	{
		if (proxyaddresses_user == null)
			getMendixObject().setValue(context, MemberNames.ProxyAddresses_User.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.ProxyAddresses_User.toString(), proxyaddresses_user.getMendixObject().getId());
	}

	/**
	 * @return value of Responsibilities_User
	 */
	public final msgraphconnector.proxies.UserResponsibilities getResponsibilities_User() throws com.mendix.core.CoreException
	{
		return getResponsibilities_User(getContext());
	}

	/**
	 * @param context
	 * @return value of Responsibilities_User
	 */
	public final msgraphconnector.proxies.UserResponsibilities getResponsibilities_User(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		msgraphconnector.proxies.UserResponsibilities result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Responsibilities_User.toString());
		if (identifier != null)
			result = msgraphconnector.proxies.UserResponsibilities.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Responsibilities_User
	 * @param responsibilities_user
	 */
	public final void setResponsibilities_User(msgraphconnector.proxies.UserResponsibilities responsibilities_user)
	{
		setResponsibilities_User(getContext(), responsibilities_user);
	}

	/**
	 * Set value of Responsibilities_User
	 * @param context
	 * @param responsibilities_user
	 */
	public final void setResponsibilities_User(com.mendix.systemwideinterfaces.core.IContext context, msgraphconnector.proxies.UserResponsibilities responsibilities_user)
	{
		if (responsibilities_user == null)
			getMendixObject().setValue(context, MemberNames.Responsibilities_User.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Responsibilities_User.toString(), responsibilities_user.getMendixObject().getId());
	}

	/**
	 * @return value of Schools_User
	 */
	public final msgraphconnector.proxies.UserSchools getSchools_User() throws com.mendix.core.CoreException
	{
		return getSchools_User(getContext());
	}

	/**
	 * @param context
	 * @return value of Schools_User
	 */
	public final msgraphconnector.proxies.UserSchools getSchools_User(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		msgraphconnector.proxies.UserSchools result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Schools_User.toString());
		if (identifier != null)
			result = msgraphconnector.proxies.UserSchools.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Schools_User
	 * @param schools_user
	 */
	public final void setSchools_User(msgraphconnector.proxies.UserSchools schools_user)
	{
		setSchools_User(getContext(), schools_user);
	}

	/**
	 * Set value of Schools_User
	 * @param context
	 * @param schools_user
	 */
	public final void setSchools_User(com.mendix.systemwideinterfaces.core.IContext context, msgraphconnector.proxies.UserSchools schools_user)
	{
		if (schools_user == null)
			getMendixObject().setValue(context, MemberNames.Schools_User.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Schools_User.toString(), schools_user.getMendixObject().getId());
	}

	/**
	 * @return value of Skills_User
	 */
	public final msgraphconnector.proxies.UserSkills getSkills_User() throws com.mendix.core.CoreException
	{
		return getSkills_User(getContext());
	}

	/**
	 * @param context
	 * @return value of Skills_User
	 */
	public final msgraphconnector.proxies.UserSkills getSkills_User(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		msgraphconnector.proxies.UserSkills result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Skills_User.toString());
		if (identifier != null)
			result = msgraphconnector.proxies.UserSkills.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Skills_User
	 * @param skills_user
	 */
	public final void setSkills_User(msgraphconnector.proxies.UserSkills skills_user)
	{
		setSkills_User(getContext(), skills_user);
	}

	/**
	 * Set value of Skills_User
	 * @param context
	 * @param skills_user
	 */
	public final void setSkills_User(com.mendix.systemwideinterfaces.core.IContext context, msgraphconnector.proxies.UserSkills skills_user)
	{
		if (skills_user == null)
			getMendixObject().setValue(context, MemberNames.Skills_User.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Skills_User.toString(), skills_user.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return userMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final msgraphconnector.proxies.User that = (msgraphconnector.proxies.User) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MSGraphConnector.User";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
