// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package msgraphconnector.proxies;

public class UserScheduledEndDateTime
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject userScheduledEndDateTimeMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MSGraphConnector.UserScheduledEndDateTime";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		DateTime("DateTime"),
		TimeZone("TimeZone"),
		ScheduledEndDateTime_AutomaticRepliesSetting("MSGraphConnector.ScheduledEndDateTime_AutomaticRepliesSetting");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public UserScheduledEndDateTime(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MSGraphConnector.UserScheduledEndDateTime"));
	}

	protected UserScheduledEndDateTime(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject userScheduledEndDateTimeMendixObject)
	{
		if (userScheduledEndDateTimeMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MSGraphConnector.UserScheduledEndDateTime", userScheduledEndDateTimeMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MSGraphConnector.UserScheduledEndDateTime");

		this.userScheduledEndDateTimeMendixObject = userScheduledEndDateTimeMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'UserScheduledEndDateTime.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static msgraphconnector.proxies.UserScheduledEndDateTime initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return msgraphconnector.proxies.UserScheduledEndDateTime.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static msgraphconnector.proxies.UserScheduledEndDateTime initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new msgraphconnector.proxies.UserScheduledEndDateTime(context, mendixObject);
	}

	public static msgraphconnector.proxies.UserScheduledEndDateTime load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return msgraphconnector.proxies.UserScheduledEndDateTime.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of DateTime
	 */
	public final java.lang.String getDateTime()
	{
		return getDateTime(getContext());
	}

	/**
	 * @param context
	 * @return value of DateTime
	 */
	public final java.lang.String getDateTime(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.DateTime.toString());
	}

	/**
	 * Set value of DateTime
	 * @param datetime
	 */
	public final void setDateTime(java.lang.String datetime)
	{
		setDateTime(getContext(), datetime);
	}

	/**
	 * Set value of DateTime
	 * @param context
	 * @param datetime
	 */
	public final void setDateTime(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String datetime)
	{
		getMendixObject().setValue(context, MemberNames.DateTime.toString(), datetime);
	}

	/**
	 * @return value of TimeZone
	 */
	public final java.lang.String getTimeZone()
	{
		return getTimeZone(getContext());
	}

	/**
	 * @param context
	 * @return value of TimeZone
	 */
	public final java.lang.String getTimeZone(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.TimeZone.toString());
	}

	/**
	 * Set value of TimeZone
	 * @param timezone
	 */
	public final void setTimeZone(java.lang.String timezone)
	{
		setTimeZone(getContext(), timezone);
	}

	/**
	 * Set value of TimeZone
	 * @param context
	 * @param timezone
	 */
	public final void setTimeZone(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String timezone)
	{
		getMendixObject().setValue(context, MemberNames.TimeZone.toString(), timezone);
	}

	/**
	 * @return value of ScheduledEndDateTime_AutomaticRepliesSetting
	 */
	public final msgraphconnector.proxies.UserAutomaticRepliesSetting getScheduledEndDateTime_AutomaticRepliesSetting() throws com.mendix.core.CoreException
	{
		return getScheduledEndDateTime_AutomaticRepliesSetting(getContext());
	}

	/**
	 * @param context
	 * @return value of ScheduledEndDateTime_AutomaticRepliesSetting
	 */
	public final msgraphconnector.proxies.UserAutomaticRepliesSetting getScheduledEndDateTime_AutomaticRepliesSetting(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		msgraphconnector.proxies.UserAutomaticRepliesSetting result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ScheduledEndDateTime_AutomaticRepliesSetting.toString());
		if (identifier != null)
			result = msgraphconnector.proxies.UserAutomaticRepliesSetting.load(context, identifier);
		return result;
	}

	/**
	 * Set value of ScheduledEndDateTime_AutomaticRepliesSetting
	 * @param scheduledenddatetime_automaticrepliessetting
	 */
	public final void setScheduledEndDateTime_AutomaticRepliesSetting(msgraphconnector.proxies.UserAutomaticRepliesSetting scheduledenddatetime_automaticrepliessetting)
	{
		setScheduledEndDateTime_AutomaticRepliesSetting(getContext(), scheduledenddatetime_automaticrepliessetting);
	}

	/**
	 * Set value of ScheduledEndDateTime_AutomaticRepliesSetting
	 * @param context
	 * @param scheduledenddatetime_automaticrepliessetting
	 */
	public final void setScheduledEndDateTime_AutomaticRepliesSetting(com.mendix.systemwideinterfaces.core.IContext context, msgraphconnector.proxies.UserAutomaticRepliesSetting scheduledenddatetime_automaticrepliessetting)
	{
		if (scheduledenddatetime_automaticrepliessetting == null)
			getMendixObject().setValue(context, MemberNames.ScheduledEndDateTime_AutomaticRepliesSetting.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.ScheduledEndDateTime_AutomaticRepliesSetting.toString(), scheduledenddatetime_automaticrepliessetting.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return userScheduledEndDateTimeMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final msgraphconnector.proxies.UserScheduledEndDateTime that = (msgraphconnector.proxies.UserScheduledEndDateTime) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MSGraphConnector.UserScheduledEndDateTime";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
