// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package msgraphconnector.proxies;

public class UserLanguage
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject userLanguageMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MSGraphConnector.UserLanguage";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Locale("Locale"),
		DisplayName("DisplayName"),
		Language_MailboxSettings("MSGraphConnector.Language_MailboxSettings");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public UserLanguage(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MSGraphConnector.UserLanguage"));
	}

	protected UserLanguage(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject userLanguageMendixObject)
	{
		if (userLanguageMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MSGraphConnector.UserLanguage", userLanguageMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MSGraphConnector.UserLanguage");

		this.userLanguageMendixObject = userLanguageMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'UserLanguage.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static msgraphconnector.proxies.UserLanguage initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return msgraphconnector.proxies.UserLanguage.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static msgraphconnector.proxies.UserLanguage initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new msgraphconnector.proxies.UserLanguage(context, mendixObject);
	}

	public static msgraphconnector.proxies.UserLanguage load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return msgraphconnector.proxies.UserLanguage.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Locale
	 */
	public final java.lang.String getLocale()
	{
		return getLocale(getContext());
	}

	/**
	 * @param context
	 * @return value of Locale
	 */
	public final java.lang.String getLocale(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Locale.toString());
	}

	/**
	 * Set value of Locale
	 * @param locale
	 */
	public final void setLocale(java.lang.String locale)
	{
		setLocale(getContext(), locale);
	}

	/**
	 * Set value of Locale
	 * @param context
	 * @param locale
	 */
	public final void setLocale(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String locale)
	{
		getMendixObject().setValue(context, MemberNames.Locale.toString(), locale);
	}

	/**
	 * @return value of DisplayName
	 */
	public final java.lang.String getDisplayName()
	{
		return getDisplayName(getContext());
	}

	/**
	 * @param context
	 * @return value of DisplayName
	 */
	public final java.lang.String getDisplayName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.DisplayName.toString());
	}

	/**
	 * Set value of DisplayName
	 * @param displayname
	 */
	public final void setDisplayName(java.lang.String displayname)
	{
		setDisplayName(getContext(), displayname);
	}

	/**
	 * Set value of DisplayName
	 * @param context
	 * @param displayname
	 */
	public final void setDisplayName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String displayname)
	{
		getMendixObject().setValue(context, MemberNames.DisplayName.toString(), displayname);
	}

	/**
	 * @return value of Language_MailboxSettings
	 */
	public final msgraphconnector.proxies.UserMailboxSettings getLanguage_MailboxSettings() throws com.mendix.core.CoreException
	{
		return getLanguage_MailboxSettings(getContext());
	}

	/**
	 * @param context
	 * @return value of Language_MailboxSettings
	 */
	public final msgraphconnector.proxies.UserMailboxSettings getLanguage_MailboxSettings(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		msgraphconnector.proxies.UserMailboxSettings result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Language_MailboxSettings.toString());
		if (identifier != null)
			result = msgraphconnector.proxies.UserMailboxSettings.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Language_MailboxSettings
	 * @param language_mailboxsettings
	 */
	public final void setLanguage_MailboxSettings(msgraphconnector.proxies.UserMailboxSettings language_mailboxsettings)
	{
		setLanguage_MailboxSettings(getContext(), language_mailboxsettings);
	}

	/**
	 * Set value of Language_MailboxSettings
	 * @param context
	 * @param language_mailboxsettings
	 */
	public final void setLanguage_MailboxSettings(com.mendix.systemwideinterfaces.core.IContext context, msgraphconnector.proxies.UserMailboxSettings language_mailboxsettings)
	{
		if (language_mailboxsettings == null)
			getMendixObject().setValue(context, MemberNames.Language_MailboxSettings.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Language_MailboxSettings.toString(), language_mailboxsettings.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return userLanguageMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final msgraphconnector.proxies.UserLanguage that = (msgraphconnector.proxies.UserLanguage) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MSGraphConnector.UserLanguage";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
