// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package msgraphconnector.proxies;

public class UserMailboxSettings
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject userMailboxSettingsMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MSGraphConnector.UserMailboxSettings";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		TimeZone("TimeZone"),
		AutomaticRepliesSetting_MailboxSettings("MSGraphConnector.AutomaticRepliesSetting_MailboxSettings"),
		Language_MailboxSettings("MSGraphConnector.Language_MailboxSettings"),
		MailboxSettings_User("MSGraphConnector.MailboxSettings_User");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public UserMailboxSettings(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MSGraphConnector.UserMailboxSettings"));
	}

	protected UserMailboxSettings(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject userMailboxSettingsMendixObject)
	{
		if (userMailboxSettingsMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MSGraphConnector.UserMailboxSettings", userMailboxSettingsMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MSGraphConnector.UserMailboxSettings");

		this.userMailboxSettingsMendixObject = userMailboxSettingsMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'UserMailboxSettings.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static msgraphconnector.proxies.UserMailboxSettings initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return msgraphconnector.proxies.UserMailboxSettings.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static msgraphconnector.proxies.UserMailboxSettings initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new msgraphconnector.proxies.UserMailboxSettings(context, mendixObject);
	}

	public static msgraphconnector.proxies.UserMailboxSettings load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return msgraphconnector.proxies.UserMailboxSettings.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of TimeZone
	 */
	public final java.lang.String getTimeZone()
	{
		return getTimeZone(getContext());
	}

	/**
	 * @param context
	 * @return value of TimeZone
	 */
	public final java.lang.String getTimeZone(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.TimeZone.toString());
	}

	/**
	 * Set value of TimeZone
	 * @param timezone
	 */
	public final void setTimeZone(java.lang.String timezone)
	{
		setTimeZone(getContext(), timezone);
	}

	/**
	 * Set value of TimeZone
	 * @param context
	 * @param timezone
	 */
	public final void setTimeZone(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String timezone)
	{
		getMendixObject().setValue(context, MemberNames.TimeZone.toString(), timezone);
	}

	/**
	 * @return value of AutomaticRepliesSetting_MailboxSettings
	 */
	public final msgraphconnector.proxies.UserAutomaticRepliesSetting getAutomaticRepliesSetting_MailboxSettings() throws com.mendix.core.CoreException
	{
		return getAutomaticRepliesSetting_MailboxSettings(getContext());
	}

	/**
	 * @param context
	 * @return value of AutomaticRepliesSetting_MailboxSettings
	 */
	public final msgraphconnector.proxies.UserAutomaticRepliesSetting getAutomaticRepliesSetting_MailboxSettings(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		msgraphconnector.proxies.UserAutomaticRepliesSetting result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.AutomaticRepliesSetting_MailboxSettings.toString());
		if (identifier != null)
			result = msgraphconnector.proxies.UserAutomaticRepliesSetting.load(context, identifier);
		return result;
	}

	/**
	 * Set value of AutomaticRepliesSetting_MailboxSettings
	 * @param automaticrepliessetting_mailboxsettings
	 */
	public final void setAutomaticRepliesSetting_MailboxSettings(msgraphconnector.proxies.UserAutomaticRepliesSetting automaticrepliessetting_mailboxsettings)
	{
		setAutomaticRepliesSetting_MailboxSettings(getContext(), automaticrepliessetting_mailboxsettings);
	}

	/**
	 * Set value of AutomaticRepliesSetting_MailboxSettings
	 * @param context
	 * @param automaticrepliessetting_mailboxsettings
	 */
	public final void setAutomaticRepliesSetting_MailboxSettings(com.mendix.systemwideinterfaces.core.IContext context, msgraphconnector.proxies.UserAutomaticRepliesSetting automaticrepliessetting_mailboxsettings)
	{
		if (automaticrepliessetting_mailboxsettings == null)
			getMendixObject().setValue(context, MemberNames.AutomaticRepliesSetting_MailboxSettings.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.AutomaticRepliesSetting_MailboxSettings.toString(), automaticrepliessetting_mailboxsettings.getMendixObject().getId());
	}

	/**
	 * @return value of Language_MailboxSettings
	 */
	public final msgraphconnector.proxies.UserLanguage getLanguage_MailboxSettings() throws com.mendix.core.CoreException
	{
		return getLanguage_MailboxSettings(getContext());
	}

	/**
	 * @param context
	 * @return value of Language_MailboxSettings
	 */
	public final msgraphconnector.proxies.UserLanguage getLanguage_MailboxSettings(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		msgraphconnector.proxies.UserLanguage result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Language_MailboxSettings.toString());
		if (identifier != null)
			result = msgraphconnector.proxies.UserLanguage.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Language_MailboxSettings
	 * @param language_mailboxsettings
	 */
	public final void setLanguage_MailboxSettings(msgraphconnector.proxies.UserLanguage language_mailboxsettings)
	{
		setLanguage_MailboxSettings(getContext(), language_mailboxsettings);
	}

	/**
	 * Set value of Language_MailboxSettings
	 * @param context
	 * @param language_mailboxsettings
	 */
	public final void setLanguage_MailboxSettings(com.mendix.systemwideinterfaces.core.IContext context, msgraphconnector.proxies.UserLanguage language_mailboxsettings)
	{
		if (language_mailboxsettings == null)
			getMendixObject().setValue(context, MemberNames.Language_MailboxSettings.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Language_MailboxSettings.toString(), language_mailboxsettings.getMendixObject().getId());
	}

	/**
	 * @return value of MailboxSettings_User
	 */
	public final msgraphconnector.proxies.User getMailboxSettings_User() throws com.mendix.core.CoreException
	{
		return getMailboxSettings_User(getContext());
	}

	/**
	 * @param context
	 * @return value of MailboxSettings_User
	 */
	public final msgraphconnector.proxies.User getMailboxSettings_User(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		msgraphconnector.proxies.User result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.MailboxSettings_User.toString());
		if (identifier != null)
			result = msgraphconnector.proxies.User.load(context, identifier);
		return result;
	}

	/**
	 * Set value of MailboxSettings_User
	 * @param mailboxsettings_user
	 */
	public final void setMailboxSettings_User(msgraphconnector.proxies.User mailboxsettings_user)
	{
		setMailboxSettings_User(getContext(), mailboxsettings_user);
	}

	/**
	 * Set value of MailboxSettings_User
	 * @param context
	 * @param mailboxsettings_user
	 */
	public final void setMailboxSettings_User(com.mendix.systemwideinterfaces.core.IContext context, msgraphconnector.proxies.User mailboxsettings_user)
	{
		if (mailboxsettings_user == null)
			getMendixObject().setValue(context, MemberNames.MailboxSettings_User.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.MailboxSettings_User.toString(), mailboxsettings_user.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return userMailboxSettingsMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final msgraphconnector.proxies.UserMailboxSettings that = (msgraphconnector.proxies.UserMailboxSettings) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MSGraphConnector.UserMailboxSettings";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
