// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package msgraphconnector.proxies;

public class UserAutomaticRepliesSetting
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject userAutomaticRepliesSettingMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MSGraphConnector.UserAutomaticRepliesSetting";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ExternalAudience("ExternalAudience"),
		ExternalReplyMessage("ExternalReplyMessage"),
		InternalReplyMessage("InternalReplyMessage"),
		Status("Status"),
		AutomaticRepliesSetting_MailboxSettings("MSGraphConnector.AutomaticRepliesSetting_MailboxSettings"),
		ScheduledStartDateTime_AutomaticRepliesSetting("MSGraphConnector.ScheduledStartDateTime_AutomaticRepliesSetting"),
		ScheduledEndDateTime_AutomaticRepliesSetting("MSGraphConnector.ScheduledEndDateTime_AutomaticRepliesSetting");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public UserAutomaticRepliesSetting(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MSGraphConnector.UserAutomaticRepliesSetting"));
	}

	protected UserAutomaticRepliesSetting(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject userAutomaticRepliesSettingMendixObject)
	{
		if (userAutomaticRepliesSettingMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MSGraphConnector.UserAutomaticRepliesSetting", userAutomaticRepliesSettingMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MSGraphConnector.UserAutomaticRepliesSetting");

		this.userAutomaticRepliesSettingMendixObject = userAutomaticRepliesSettingMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'UserAutomaticRepliesSetting.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static msgraphconnector.proxies.UserAutomaticRepliesSetting initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return msgraphconnector.proxies.UserAutomaticRepliesSetting.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static msgraphconnector.proxies.UserAutomaticRepliesSetting initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new msgraphconnector.proxies.UserAutomaticRepliesSetting(context, mendixObject);
	}

	public static msgraphconnector.proxies.UserAutomaticRepliesSetting load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return msgraphconnector.proxies.UserAutomaticRepliesSetting.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * Set value of ExternalAudience
	 * @param externalaudience
	 */
	public final msgraphconnector.proxies.AutomaticRepliesSettingExternalAudience getExternalAudience()
	{
		return getExternalAudience(getContext());
	}

	/**
	 * @param context
	 * @return value of ExternalAudience
	 */
	public final msgraphconnector.proxies.AutomaticRepliesSettingExternalAudience getExternalAudience(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.ExternalAudience.toString());
		if (obj == null)
			return null;

		return msgraphconnector.proxies.AutomaticRepliesSettingExternalAudience.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of ExternalAudience
	 * @param externalaudience
	 */
	public final void setExternalAudience(msgraphconnector.proxies.AutomaticRepliesSettingExternalAudience externalaudience)
	{
		setExternalAudience(getContext(), externalaudience);
	}

	/**
	 * Set value of ExternalAudience
	 * @param context
	 * @param externalaudience
	 */
	public final void setExternalAudience(com.mendix.systemwideinterfaces.core.IContext context, msgraphconnector.proxies.AutomaticRepliesSettingExternalAudience externalaudience)
	{
		if (externalaudience != null)
			getMendixObject().setValue(context, MemberNames.ExternalAudience.toString(), externalaudience.toString());
		else
			getMendixObject().setValue(context, MemberNames.ExternalAudience.toString(), null);
	}

	/**
	 * @return value of ExternalReplyMessage
	 */
	public final java.lang.String getExternalReplyMessage()
	{
		return getExternalReplyMessage(getContext());
	}

	/**
	 * @param context
	 * @return value of ExternalReplyMessage
	 */
	public final java.lang.String getExternalReplyMessage(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ExternalReplyMessage.toString());
	}

	/**
	 * Set value of ExternalReplyMessage
	 * @param externalreplymessage
	 */
	public final void setExternalReplyMessage(java.lang.String externalreplymessage)
	{
		setExternalReplyMessage(getContext(), externalreplymessage);
	}

	/**
	 * Set value of ExternalReplyMessage
	 * @param context
	 * @param externalreplymessage
	 */
	public final void setExternalReplyMessage(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String externalreplymessage)
	{
		getMendixObject().setValue(context, MemberNames.ExternalReplyMessage.toString(), externalreplymessage);
	}

	/**
	 * @return value of InternalReplyMessage
	 */
	public final java.lang.String getInternalReplyMessage()
	{
		return getInternalReplyMessage(getContext());
	}

	/**
	 * @param context
	 * @return value of InternalReplyMessage
	 */
	public final java.lang.String getInternalReplyMessage(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.InternalReplyMessage.toString());
	}

	/**
	 * Set value of InternalReplyMessage
	 * @param internalreplymessage
	 */
	public final void setInternalReplyMessage(java.lang.String internalreplymessage)
	{
		setInternalReplyMessage(getContext(), internalreplymessage);
	}

	/**
	 * Set value of InternalReplyMessage
	 * @param context
	 * @param internalreplymessage
	 */
	public final void setInternalReplyMessage(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String internalreplymessage)
	{
		getMendixObject().setValue(context, MemberNames.InternalReplyMessage.toString(), internalreplymessage);
	}

	/**
	 * Set value of Status
	 * @param status
	 */
	public final msgraphconnector.proxies.AutomaticRepliesSettingStatus getStatus()
	{
		return getStatus(getContext());
	}

	/**
	 * @param context
	 * @return value of Status
	 */
	public final msgraphconnector.proxies.AutomaticRepliesSettingStatus getStatus(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Status.toString());
		if (obj == null)
			return null;

		return msgraphconnector.proxies.AutomaticRepliesSettingStatus.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Status
	 * @param status
	 */
	public final void setStatus(msgraphconnector.proxies.AutomaticRepliesSettingStatus status)
	{
		setStatus(getContext(), status);
	}

	/**
	 * Set value of Status
	 * @param context
	 * @param status
	 */
	public final void setStatus(com.mendix.systemwideinterfaces.core.IContext context, msgraphconnector.proxies.AutomaticRepliesSettingStatus status)
	{
		if (status != null)
			getMendixObject().setValue(context, MemberNames.Status.toString(), status.toString());
		else
			getMendixObject().setValue(context, MemberNames.Status.toString(), null);
	}

	/**
	 * @return value of AutomaticRepliesSetting_MailboxSettings
	 */
	public final msgraphconnector.proxies.UserMailboxSettings getAutomaticRepliesSetting_MailboxSettings() throws com.mendix.core.CoreException
	{
		return getAutomaticRepliesSetting_MailboxSettings(getContext());
	}

	/**
	 * @param context
	 * @return value of AutomaticRepliesSetting_MailboxSettings
	 */
	public final msgraphconnector.proxies.UserMailboxSettings getAutomaticRepliesSetting_MailboxSettings(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		msgraphconnector.proxies.UserMailboxSettings result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.AutomaticRepliesSetting_MailboxSettings.toString());
		if (identifier != null)
			result = msgraphconnector.proxies.UserMailboxSettings.load(context, identifier);
		return result;
	}

	/**
	 * Set value of AutomaticRepliesSetting_MailboxSettings
	 * @param automaticrepliessetting_mailboxsettings
	 */
	public final void setAutomaticRepliesSetting_MailboxSettings(msgraphconnector.proxies.UserMailboxSettings automaticrepliessetting_mailboxsettings)
	{
		setAutomaticRepliesSetting_MailboxSettings(getContext(), automaticrepliessetting_mailboxsettings);
	}

	/**
	 * Set value of AutomaticRepliesSetting_MailboxSettings
	 * @param context
	 * @param automaticrepliessetting_mailboxsettings
	 */
	public final void setAutomaticRepliesSetting_MailboxSettings(com.mendix.systemwideinterfaces.core.IContext context, msgraphconnector.proxies.UserMailboxSettings automaticrepliessetting_mailboxsettings)
	{
		if (automaticrepliessetting_mailboxsettings == null)
			getMendixObject().setValue(context, MemberNames.AutomaticRepliesSetting_MailboxSettings.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.AutomaticRepliesSetting_MailboxSettings.toString(), automaticrepliessetting_mailboxsettings.getMendixObject().getId());
	}

	/**
	 * @return value of ScheduledStartDateTime_AutomaticRepliesSetting
	 */
	public final msgraphconnector.proxies.UserScheduledStartDateTime getScheduledStartDateTime_AutomaticRepliesSetting() throws com.mendix.core.CoreException
	{
		return getScheduledStartDateTime_AutomaticRepliesSetting(getContext());
	}

	/**
	 * @param context
	 * @return value of ScheduledStartDateTime_AutomaticRepliesSetting
	 */
	public final msgraphconnector.proxies.UserScheduledStartDateTime getScheduledStartDateTime_AutomaticRepliesSetting(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		msgraphconnector.proxies.UserScheduledStartDateTime result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ScheduledStartDateTime_AutomaticRepliesSetting.toString());
		if (identifier != null)
			result = msgraphconnector.proxies.UserScheduledStartDateTime.load(context, identifier);
		return result;
	}

	/**
	 * Set value of ScheduledStartDateTime_AutomaticRepliesSetting
	 * @param scheduledstartdatetime_automaticrepliessetting
	 */
	public final void setScheduledStartDateTime_AutomaticRepliesSetting(msgraphconnector.proxies.UserScheduledStartDateTime scheduledstartdatetime_automaticrepliessetting)
	{
		setScheduledStartDateTime_AutomaticRepliesSetting(getContext(), scheduledstartdatetime_automaticrepliessetting);
	}

	/**
	 * Set value of ScheduledStartDateTime_AutomaticRepliesSetting
	 * @param context
	 * @param scheduledstartdatetime_automaticrepliessetting
	 */
	public final void setScheduledStartDateTime_AutomaticRepliesSetting(com.mendix.systemwideinterfaces.core.IContext context, msgraphconnector.proxies.UserScheduledStartDateTime scheduledstartdatetime_automaticrepliessetting)
	{
		if (scheduledstartdatetime_automaticrepliessetting == null)
			getMendixObject().setValue(context, MemberNames.ScheduledStartDateTime_AutomaticRepliesSetting.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.ScheduledStartDateTime_AutomaticRepliesSetting.toString(), scheduledstartdatetime_automaticrepliessetting.getMendixObject().getId());
	}

	/**
	 * @return value of ScheduledEndDateTime_AutomaticRepliesSetting
	 */
	public final msgraphconnector.proxies.UserScheduledEndDateTime getScheduledEndDateTime_AutomaticRepliesSetting() throws com.mendix.core.CoreException
	{
		return getScheduledEndDateTime_AutomaticRepliesSetting(getContext());
	}

	/**
	 * @param context
	 * @return value of ScheduledEndDateTime_AutomaticRepliesSetting
	 */
	public final msgraphconnector.proxies.UserScheduledEndDateTime getScheduledEndDateTime_AutomaticRepliesSetting(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		msgraphconnector.proxies.UserScheduledEndDateTime result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ScheduledEndDateTime_AutomaticRepliesSetting.toString());
		if (identifier != null)
			result = msgraphconnector.proxies.UserScheduledEndDateTime.load(context, identifier);
		return result;
	}

	/**
	 * Set value of ScheduledEndDateTime_AutomaticRepliesSetting
	 * @param scheduledenddatetime_automaticrepliessetting
	 */
	public final void setScheduledEndDateTime_AutomaticRepliesSetting(msgraphconnector.proxies.UserScheduledEndDateTime scheduledenddatetime_automaticrepliessetting)
	{
		setScheduledEndDateTime_AutomaticRepliesSetting(getContext(), scheduledenddatetime_automaticrepliessetting);
	}

	/**
	 * Set value of ScheduledEndDateTime_AutomaticRepliesSetting
	 * @param context
	 * @param scheduledenddatetime_automaticrepliessetting
	 */
	public final void setScheduledEndDateTime_AutomaticRepliesSetting(com.mendix.systemwideinterfaces.core.IContext context, msgraphconnector.proxies.UserScheduledEndDateTime scheduledenddatetime_automaticrepliessetting)
	{
		if (scheduledenddatetime_automaticrepliessetting == null)
			getMendixObject().setValue(context, MemberNames.ScheduledEndDateTime_AutomaticRepliesSetting.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.ScheduledEndDateTime_AutomaticRepliesSetting.toString(), scheduledenddatetime_automaticrepliessetting.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return userAutomaticRepliesSettingMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final msgraphconnector.proxies.UserAutomaticRepliesSetting that = (msgraphconnector.proxies.UserAutomaticRepliesSetting) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MSGraphConnector.UserAutomaticRepliesSetting";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
