// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package msgraphconnector.proxies;

public class UserPasswordProfile
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject userPasswordProfileMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MSGraphConnector.UserPasswordProfile";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ForceChangePasswordNextSignIn("ForceChangePasswordNextSignIn"),
		Password("Password"),
		PasswordProfile_User("MSGraphConnector.PasswordProfile_User");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public UserPasswordProfile(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MSGraphConnector.UserPasswordProfile"));
	}

	protected UserPasswordProfile(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject userPasswordProfileMendixObject)
	{
		if (userPasswordProfileMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MSGraphConnector.UserPasswordProfile", userPasswordProfileMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MSGraphConnector.UserPasswordProfile");

		this.userPasswordProfileMendixObject = userPasswordProfileMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'UserPasswordProfile.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static msgraphconnector.proxies.UserPasswordProfile initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return msgraphconnector.proxies.UserPasswordProfile.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static msgraphconnector.proxies.UserPasswordProfile initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new msgraphconnector.proxies.UserPasswordProfile(context, mendixObject);
	}

	public static msgraphconnector.proxies.UserPasswordProfile load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return msgraphconnector.proxies.UserPasswordProfile.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of ForceChangePasswordNextSignIn
	 */
	public final java.lang.Boolean getForceChangePasswordNextSignIn()
	{
		return getForceChangePasswordNextSignIn(getContext());
	}

	/**
	 * @param context
	 * @return value of ForceChangePasswordNextSignIn
	 */
	public final java.lang.Boolean getForceChangePasswordNextSignIn(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ForceChangePasswordNextSignIn.toString());
	}

	/**
	 * Set value of ForceChangePasswordNextSignIn
	 * @param forcechangepasswordnextsignin
	 */
	public final void setForceChangePasswordNextSignIn(java.lang.Boolean forcechangepasswordnextsignin)
	{
		setForceChangePasswordNextSignIn(getContext(), forcechangepasswordnextsignin);
	}

	/**
	 * Set value of ForceChangePasswordNextSignIn
	 * @param context
	 * @param forcechangepasswordnextsignin
	 */
	public final void setForceChangePasswordNextSignIn(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean forcechangepasswordnextsignin)
	{
		getMendixObject().setValue(context, MemberNames.ForceChangePasswordNextSignIn.toString(), forcechangepasswordnextsignin);
	}

	/**
	 * @return value of Password
	 */
	public final java.lang.String getPassword()
	{
		return getPassword(getContext());
	}

	/**
	 * @param context
	 * @return value of Password
	 */
	public final java.lang.String getPassword(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Password.toString());
	}

	/**
	 * Set value of Password
	 * @param password
	 */
	public final void setPassword(java.lang.String password)
	{
		setPassword(getContext(), password);
	}

	/**
	 * Set value of Password
	 * @param context
	 * @param password
	 */
	public final void setPassword(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String password)
	{
		getMendixObject().setValue(context, MemberNames.Password.toString(), password);
	}

	/**
	 * @return value of PasswordProfile_User
	 */
	public final msgraphconnector.proxies.User getPasswordProfile_User() throws com.mendix.core.CoreException
	{
		return getPasswordProfile_User(getContext());
	}

	/**
	 * @param context
	 * @return value of PasswordProfile_User
	 */
	public final msgraphconnector.proxies.User getPasswordProfile_User(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		msgraphconnector.proxies.User result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.PasswordProfile_User.toString());
		if (identifier != null)
			result = msgraphconnector.proxies.User.load(context, identifier);
		return result;
	}

	/**
	 * Set value of PasswordProfile_User
	 * @param passwordprofile_user
	 */
	public final void setPasswordProfile_User(msgraphconnector.proxies.User passwordprofile_user)
	{
		setPasswordProfile_User(getContext(), passwordprofile_user);
	}

	/**
	 * Set value of PasswordProfile_User
	 * @param context
	 * @param passwordprofile_user
	 */
	public final void setPasswordProfile_User(com.mendix.systemwideinterfaces.core.IContext context, msgraphconnector.proxies.User passwordprofile_user)
	{
		if (passwordprofile_user == null)
			getMendixObject().setValue(context, MemberNames.PasswordProfile_User.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.PasswordProfile_User.toString(), passwordprofile_user.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return userPasswordProfileMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final msgraphconnector.proxies.UserPasswordProfile that = (msgraphconnector.proxies.UserPasswordProfile) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MSGraphConnector.UserPasswordProfile";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
