// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package stringutils.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import stringutils.StringUtils;

/**
 * Creates a HMAC SHA 256 byte array and converts it into a String representing the hexadecimal values of each byte in order.
 */
public class GenerateHMAC_SHA256_HexDigest extends CustomJavaAction<java.lang.String>
{
	private java.lang.String key;
	private java.lang.String value;

	public GenerateHMAC_SHA256_HexDigest(IContext context, java.lang.String key, java.lang.String value)
	{
		super(context);
		this.key = key;
		this.value = value;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		return StringUtils.generateHmacSha256HexDigest(key, value);
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GenerateHMAC_SHA256_HexDigest";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
