// This file was generated by Mendix Modeler 7.3.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package msgraphconnector.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the microflows for the MSGraphConnector module
	public static boolean authoriseUser(IContext context, java.lang.String _code, system.proxies.User _user)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("code", _code);
			params.put("User", _user == null ? null : _user.getMendixObject());
			return (java.lang.Boolean)Core.execute(context, "MSGraphConnector.AuthoriseUser", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void cleanAccessLog(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			Core.execute(context, "MSGraphConnector.CleanAccessLog", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void cleanUpExpiredAuthTokens(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			Core.execute(context, "MSGraphConnector.CleanUpExpiredAuthTokens", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static java.lang.String convertNextLinkToUrlParams(IContext context, java.lang.String __odata_nextLink)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("_odata_nextLink", __odata_nextLink);
			return (java.lang.String)Core.execute(context, "MSGraphConnector.ConvertNextLinkToUrlParams", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void createApplicationDefaultPermissions(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			Core.execute(context, "MSGraphConnector.CreateApplicationDefaultPermissions", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static boolean dELETE_DeleteUser(IContext context, msgraphconnector.proxies.AuthToken _authToken, java.lang.String _userId)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("AuthToken", _authToken == null ? null : _authToken.getMendixObject());
			params.put("UserId", _userId);
			return (java.lang.Boolean)Core.execute(context, "MSGraphConnector.DELETE_DeleteUser", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void deleteAndCreateApplicationDefaultPermissions(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			Core.execute(context, "MSGraphConnector.DeleteAndCreateApplicationDefaultPermissions", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void deleteApplicationPermissions(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			Core.execute(context, "MSGraphConnector.DeleteApplicationPermissions", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static msgraphconnector.proxies.AuthToken findUserToken(IContext context, system.proxies.User _user)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("User", _user == null ? null : _user.getMendixObject());
			IMendixObject result = (IMendixObject)Core.execute(context, "MSGraphConnector.FindUserToken", params);
			return result == null ? null : msgraphconnector.proxies.AuthToken.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static msgraphconnector.proxies.User gET_GetMyUser(IContext context, msgraphconnector.proxies.AuthToken _authToken)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("AuthToken", _authToken == null ? null : _authToken.getMendixObject());
			IMendixObject result = (IMendixObject)Core.execute(context, "MSGraphConnector.GET_GetMyUser", params);
			return result == null ? null : msgraphconnector.proxies.User.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static msgraphconnector.proxies.User gET_GetUserByEmail(IContext context, msgraphconnector.proxies.AuthToken _authToken, java.lang.String _email)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("AuthToken", _authToken == null ? null : _authToken.getMendixObject());
			params.put("Email", _email);
			IMendixObject result = (IMendixObject)Core.execute(context, "MSGraphConnector.GET_GetUserByEmail", params);
			return result == null ? null : msgraphconnector.proxies.User.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static msgraphconnector.proxies.User gET_GetUserById(IContext context, msgraphconnector.proxies.AuthToken _authToken, java.lang.String _userId)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("AuthToken", _authToken == null ? null : _authToken.getMendixObject());
			params.put("UserId", _userId);
			IMendixObject result = (IMendixObject)Core.execute(context, "MSGraphConnector.GET_GetUserById", params);
			return result == null ? null : msgraphconnector.proxies.User.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static msgraphconnector.proxies.User gET_GetUserByPrincipalName(IContext context, msgraphconnector.proxies.AuthToken _authToken, java.lang.String _principalName)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("AuthToken", _authToken == null ? null : _authToken.getMendixObject());
			params.put("PrincipalName", _principalName);
			IMendixObject result = (IMendixObject)Core.execute(context, "MSGraphConnector.GET_GetUserByPrincipalName", params);
			return result == null ? null : msgraphconnector.proxies.User.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static msgraphconnector.proxies.Result gET_ListUsers(IContext context, msgraphconnector.proxies.AuthToken _authToken, java.lang.String _queryParams)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("AuthToken", _authToken == null ? null : _authToken.getMendixObject());
			params.put("QueryParams", _queryParams);
			IMendixObject result = (IMendixObject)Core.execute(context, "MSGraphConnector.GET_ListUsers", params);
			return result == null ? null : msgraphconnector.proxies.Result.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static msgraphconnector.proxies.Result getAllOrgUsers(IContext context, java.lang.String _queryParams)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("QueryParams", _queryParams);
			IMendixObject result = (IMendixObject)Core.execute(context, "MSGraphConnector.GetAllOrgUsers", params);
			return result == null ? null : msgraphconnector.proxies.Result.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static java.lang.String getApplicationPermission_AsString(IContext context, msgraphconnector.proxies.Application _application)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Application", _application == null ? null : _application.getMendixObject());
			return (java.lang.String)Core.execute(context, "MSGraphConnector.GetApplicationPermission_AsString", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static msgraphconnector.proxies.User getMyUserInfo(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			IMendixObject result = (IMendixObject)Core.execute(context, "MSGraphConnector.GetMyUserInfo", params);
			return result == null ? null : msgraphconnector.proxies.User.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static msgraphconnector.proxies.User getUserByEmail(IContext context, java.lang.String _email)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Email", _email);
			IMendixObject result = (IMendixObject)Core.execute(context, "MSGraphConnector.GetUserByEmail", params);
			return result == null ? null : msgraphconnector.proxies.User.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static msgraphconnector.proxies.User getUserById(IContext context, java.lang.String _user_Id)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("User_Id", _user_Id);
			IMendixObject result = (IMendixObject)Core.execute(context, "MSGraphConnector.GetUserById", params);
			return result == null ? null : msgraphconnector.proxies.User.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static msgraphconnector.proxies.User getUserByPrincipal(IContext context, java.lang.String _principalName)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("PrincipalName", _principalName);
			IMendixObject result = (IMendixObject)Core.execute(context, "MSGraphConnector.GetUserByPrincipal", params);
			return result == null ? null : msgraphconnector.proxies.User.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void handleApplicationHttpError(IContext context, msgraphconnector.proxies.Application _application, system.proxies.HttpResponse _httpResponseError)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Application", _application == null ? null : _application.getMendixObject());
			params.put("HttpResponseError", _httpResponseError == null ? null : _httpResponseError.getMendixObject());
			Core.execute(context, "MSGraphConnector.HandleApplicationHttpError", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void handleHttpError(IContext context, msgraphconnector.proxies.AuthToken _authToken, system.proxies.HttpResponse _httpResponseError)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("AuthToken", _authToken == null ? null : _authToken.getMendixObject());
			params.put("HttpResponseError", _httpResponseError == null ? null : _httpResponseError.getMendixObject());
			Core.execute(context, "MSGraphConnector.HandleHttpError", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static msgraphconnector.proxies.Application iVK_GetOrCreateMSGraphApplication(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			IMendixObject result = (IMendixObject)Core.execute(context, "MSGraphConnector.IVK_GetOrCreateMSGraphApplication", params);
			return result == null ? null : msgraphconnector.proxies.Application.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void logout(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			Core.execute(context, "MSGraphConnector.Logout", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void oC_CreateDefaultApplicationPermissions(IContext context, java.util.List<msgraphconnector.proxies.Permission> _permissionList)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			java.util.ArrayList<IMendixObject> listparam_permissionList = null;
			if (_permissionList != null)
			{
				listparam_permissionList = new java.util.ArrayList<IMendixObject>();
				for (msgraphconnector.proxies.Permission obj : _permissionList)
					listparam_permissionList.add(obj.getMendixObject());
			}
			params.put("PermissionList", listparam_permissionList);
			Core.execute(context, "MSGraphConnector.OC_CreateDefaultApplicationPermissions", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void oC_DeleteUserToken(IContext context, msgraphconnector.proxies.AuthToken _authToken)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("AuthToken", _authToken == null ? null : _authToken.getMendixObject());
			Core.execute(context, "MSGraphConnector.OC_DeleteUserToken", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void oC_GetAdminConsent(IContext context, msgraphconnector.proxies.Application _application)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Application", _application == null ? null : _application.getMendixObject());
			Core.execute(context, "MSGraphConnector.OC_GetAdminConsent", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static msgraphconnector.proxies.User pATCH_UpdateUser(IContext context, msgraphconnector.proxies.AuthToken _authToken, msgraphconnector.proxies.User _user)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("AuthToken", _authToken == null ? null : _authToken.getMendixObject());
			params.put("User", _user == null ? null : _user.getMendixObject());
			IMendixObject result = (IMendixObject)Core.execute(context, "MSGraphConnector.PATCH_UpdateUser", params);
			return result == null ? null : msgraphconnector.proxies.User.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static msgraphconnector.proxies.User pOST_CreateUser(IContext context, msgraphconnector.proxies.AuthToken _authToken, msgraphconnector.proxies.User _user)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("AuthToken", _authToken == null ? null : _authToken.getMendixObject());
			params.put("User", _user == null ? null : _user.getMendixObject());
			IMendixObject result = (IMendixObject)Core.execute(context, "MSGraphConnector.POST_CreateUser", params);
			return result == null ? null : msgraphconnector.proxies.User.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static boolean pOST_GetGraphToken(IContext context, java.lang.String _code, system.proxies.User _user)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("code", _code);
			params.put("User", _user == null ? null : _user.getMendixObject());
			return (java.lang.Boolean)Core.execute(context, "MSGraphConnector.POST_GetGraphToken", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static boolean pOST_RefreshToken(IContext context, msgraphconnector.proxies.AuthToken _refreshToken)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("RefreshToken", _refreshToken == null ? null : _refreshToken.getMendixObject());
			return (java.lang.Boolean)Core.execute(context, "MSGraphConnector.POST_RefreshToken", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static boolean refreshUserToken(IContext context, system.proxies.User _user)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("User", _user == null ? null : _user.getMendixObject());
			return (java.lang.Boolean)Core.execute(context, "MSGraphConnector.RefreshUserToken", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static system.proxies.User resolveUserByEmail(IContext context, java.lang.String _email)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Email", _email);
			IMendixObject result = (IMendixObject)Core.execute(context, "MSGraphConnector.ResolveUserByEmail", params);
			return result == null ? null : system.proxies.User.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void startWithCustomRequestHandlers(IContext context, java.lang.String _contextPath, java.lang.String _signInPath, java.lang.String _callbackPath, java.lang.String _logoutPath)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("ContextPath", _contextPath);
			params.put("SignInPath", _signInPath);
			params.put("CallbackPath", _callbackPath);
			params.put("LogoutPath", _logoutPath);
			Core.execute(context, "MSGraphConnector.StartWithCustomRequestHandlers", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void updateUser(IContext context, msgraphconnector.proxies.User _user)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("User", _user == null ? null : _user.getMendixObject());
			Core.execute(context, "MSGraphConnector.UpdateUser", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static boolean userHasValidToken(IContext context, system.proxies.User _user)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("User", _user == null ? null : _user.getMendixObject());
			return (java.lang.Boolean)Core.execute(context, "MSGraphConnector.UserHasValidToken", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
}