// This file was generated by Mendix Modeler 7.3.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package msgraphconnector.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	// These are the constants for the MSGraphConnector module

	public static java.lang.String getAdminConsentSuccessPage()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("MSGraphConnector.AdminConsentSuccessPage");
	}

	public static java.lang.String getCookieErrorPage()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("MSGraphConnector.CookieErrorPage");
	}

	public static java.lang.String getCookieName()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("MSGraphConnector.CookieName");
	}

	public static java.lang.String getErrorPage()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("MSGraphConnector.ErrorPage");
	}

	public static java.lang.String getIndexPage()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("MSGraphConnector.IndexPage");
	}

	public static java.lang.String getLogoutPage()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("MSGraphConnector.LogoutPage");
	}

	public static java.lang.String getMicrosoftGraphBaseAPIUrl()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("MSGraphConnector.MicrosoftGraphBaseAPIUrl");
	}

	public static java.lang.String getMicrosoftOnlineBaseAuthUrl()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("MSGraphConnector.MicrosoftOnlineBaseAuthUrl");
	}

	public static java.lang.String getMicrosoftOnlineBaseAuthUrlAdminConsent()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("MSGraphConnector.MicrosoftOnlineBaseAuthUrlAdminConsent");
	}

	/**
	* MSGraphConnector.ResolveUserByEmail
	*/
	public static java.lang.String getResolveUserMicroflow()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("MSGraphConnector.ResolveUserMicroflow");
	}

	public static java.lang.String getStateErrorPage()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("MSGraphConnector.StateErrorPage");
	}

	public static java.lang.String getUnauthorizedAccessPage()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("MSGraphConnector.UnauthorizedAccessPage");
	}
}