// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package msgraphconnector.actions;

import com.mendix.core.Core;
import com.mendix.externalinterface.connector.RequestHandler;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import msgraphconnector.actions.custom.MSGraphRequestHandler;

public class JA_CreateMSGraphRequestHandlers extends CustomJavaAction<java.lang.Boolean>
{
	private java.lang.String ContextPath;
	private java.lang.String SignInPath;
	private java.lang.String CallbackPath;
	private java.lang.String LogoutPath;

	public JA_CreateMSGraphRequestHandlers(IContext context, java.lang.String ContextPath, java.lang.String SignInPath, java.lang.String CallbackPath, java.lang.String LogoutPath)
	{
		super(context);
		this.ContextPath = ContextPath;
		this.SignInPath = SignInPath;
		this.CallbackPath = CallbackPath;
		this.LogoutPath = LogoutPath;
	}

	@Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		RequestHandler requestHandler = new MSGraphRequestHandler(ContextPath,SignInPath,CallbackPath,LogoutPath);
		Core.addRequestHandler(ContextPath, requestHandler);
		Core.getLogger("MSGraph").info("Registered OAuth callback request handler at context path: "+ ContextPath);

		return Boolean.TRUE;

		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "JA_CreateMSGraphRequestHandlers";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
